### ISSUE TITLE
Wrong version name on npm

### ISSUE THREAD

**Issue by Johannathorsen** [bazelbuild/buildtools#1002]
Hello!

Should the latest bazelbuild version really be 0.0.0-PLACEHOLDER? It sounds sus🕵️‍♀️
https://www.npmjs.com/package/@bazel/buildifier

**Comment by vladmos** [comment]
@alexeagle If I recall correctly, you set npm releases up, could you please take a look? The placeholder version is mentioned in the package.json file (https://github.com/bazelbuild/buildtools/blob/master/buildifier/npm/package.json and https://github.com/bazelbuild/buildtools/blob/master/buildozer/npm/package.json) but it didn't leak directly until recently (I updated rules_nodejs to 4.0.0 several days ago, that must be the reason).

**Comment by alexeagle** [comment]
ouch, that would be a nasty regression. 👀

**Comment by alexeagle** [comment]
ah, you upgraded really far! it was a breaking change in 3.0:
https://github.com/bazelbuild/rules_nodejs/releases/tag/3.0.0
> pkg_npm no longer has replace_with_version attribute, use substitutions instead

the commit that broke it includes examples that were fixed:
https://github.com/bazelbuild/rules_nodejs/commit/68b18d8#diff-17154e6431fac8568e6795870f57aa8d3743363a843ea3b5d41b25c651152500

I'll send you a PR to make that fix here as well.

note that you can fix the damage if you like: https://docs.npmjs.com/cli/v7/commands/npm-unpublish

**Comment by vladmos** [comment]
Thanks everyone, I released 4.2.1 with a correct version number and marked 4.2.0 aka 0.0.0-PLACEHOLDER as deprecated (npm won't let me to unpublish it completely).
