### ISSUE TITLE
Add a way to disable removal of redundant target qualifiers

### ISSUE THREAD

**Issue by tapthaker** [bazelbuild/buildtools#1007]
Currently, buildifer formats the following BUILD file:
```
some_rule(
         name = "SomeName",
         deps = [ "//libraries/blah:blah"],
)
```
to:
```
some_rule(
         name = "SomeName",
         deps = [ "//libraries/blah"],
)
```

Can we add an option so that buildifier does not remove redundant target qualifiers? 

If you are open to the idea, I can submit a PR that does this.

**Comment by laurentlb** [comment]
Why?

Buildifier focuses on consistency (one standard way for writing the file) and avoids new flags and customization.

**Comment by tapthaker** [comment]
> Why?
My reasoning is that buildifier did not do this earlier and we now have code that relies on fully expanded target names.
> and avoids new flags and customization
You wouldn't necessarily need new flags, we could tie it back to the `buildifier_disable` flag.
```
 -buildifier_disable string
        list of buildifier rewrites to disable
```
