### ISSUE TITLE
Buildozer doesn't have a way to remove an attribute if it has a specific value

### ISSUE THREAD

**Issue by endobson** [bazelbuild/buildtools#105]
I want to clear attributes that are set to a specific value. The use case is that an option was provided that had one default, and the default has switched. I now want to clear out all the settings where the new default is explicitly set.

**Comment by pmbethe09** [comment]
something like

buildozer 'remove someValue if someValue == "abc"' //some:target

That could be useful, but the grammar of the operation string has no support for that at this time.

**Comment by endobson** [comment]
It could be
```
buildozer 'remove_if_equal attribute_name value' //some:target
```
which would work with the existing grammar. And this is similar to `set_if_absent`.

**Comment by pmbethe09** [comment]
Ah, yes that could work.  Feel free to contribute this if it would be useful to you.
