### ISSUE TITLE
How to teach buildifer to sort string/target list arguments in macros?

### ISSUE THREAD

**Issue by sxlijin** [bazelbuild/buildtools#1095]
Given a custom macro that looks like this:

```
foo(targets = ["@alpha//:first", "//my/repo:two", "//my/repo:one"])
```

what hints can be given to buildifier to tell it that `targets` is an order-agnostic field, and that it should sort `targets`?

**Comment by pmbethe09** [comment]
2 options:

1) easy: add 
`# keep sorted`
to any label attribute that can be sorted.

2) harder: update https://github.com/bazelbuild/buildtools/blob/master/tables/tables.go

**Comment by sxlijin** [comment]
Thanks! Opened #1097.
