### ISSUE TITLE
Flag --incompatible_disable_starlark_host_transitions will break Buildtools in Bazel 7.0

### ISSUE THREAD

**Issue by keertk** [bazelbuild/buildtools#1109]
Incompatible flag `--incompatible_disable_starlark_host_transitions` will be enabled by default in the next major release (Bazel 7.0), thus breaking Buildtools. Please migrate to fix this and unblock the flip of this flag.

The flag is documented here: [bazelbuild/bazel#17032](https://github.com/bazelbuild/bazel/issues/17032).

Please check the following CI builds for build and test results:

- [MacOS OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-c5f3-47f4-be25-48f308a9fbd6)
- [Ubuntu 16.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-c5ed-4e4e-ad39-e68ea46548a1)
- [Ubuntu 18.04 OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-c5f0-4af7-9ba4-34f166f4d976)
- [Windows OpenJDK 11](https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1365#0185154a-c5f6-4abc-b52f-b97d40f52eb6)

Never heard of incompatible flags before? We have [documentation](https://docs.bazel.build/versions/master/backward-compatibility.html) that explains everything.
If you have any questions, please file an issue in https://github.com/bazelbuild/continuous-integration.

**Comment by sgowroji** [comment]
Hi @bazelbuild/buildtools team, Could you please look into this issue. Thanks!
