### ISSUE TITLE
Provide original path of artifact

### ISSUE THREAD

**Issue by mwoehlke-kitware** [bazelbuild/buildtools#111]
Since Bazel can't install things by itself, I have been working on bolting on a kludge to do it. One of the issues I run into is:

```
install_files(
    ...
    files = [
        "src/foo/example.h",
        "src/bar/example.h",
    ]
)
```

Now, I need to install these to `foo/example.h` and `bar/example.h`. Breaking up the list into multiple `install` directives would be superfluous repetition at best; in some cases, the headers may be coming from elsewhere (`transitive_headers` being a worst case).

The problem is, while Bazel knows at the point that it first sees a path that ultimately creates the artifact object that a file is named like e.g. `src/foo/example.h`, this information is lost to Skylark.

I can generally figure out what this "partial path" should be, but *only* if the artifact originates in the same context as the rule that needs to know; otherwise, the user has to manually specify a context, which leads to DRY violations.

Please make the original partial path available in Skylark.

See the argument at robotlocomotion/drake#6347 for additional context.

**Comment by pmbethe09** [comment]
This seems to be asking for skylark changes, so I think this is better suited for the main 'bazel' forum.

**Comment by mwoehlke-kitware** [comment]
https://github.com/bazelbuild/bazel/issues/3227

I blame Google search for thinking this repo is more interesting than the main repo...
