### ISSUE TITLE
Breaking repos on buildifier release

### ISSUE THREAD

**Issue by comius** [bazelbuild/buildtools#1189]
The release broke several repos because of more stringent requirements.

I’ve noticed load order in skylib.
I’ve also noticed new requirement to order rule’s attributes in a dict lexiographically. That’s what probably all of the rules are breaking.

Please consider adjusting those requirements for rules.

Please automate rerunning buildifier on all bazelbuild repos creating PRs, to eliminate the churn.

**Comment by vladmos** [comment]
The PR for sorting dict items by default has not yet been merged: https://github.com/bazelbuild/buildtools/pull/1185

What breaks the rules is probably another warning about load statements not being sorted by the label.

Do you have a dashboard with all the affected repos so that I could fix all of them?

**Comment by comius** [comment]
Interesting. I have a breakage because of sorted dict in rules_java, cl pending: https://buildkite.com/bazel/google-rules-java-presubmit/builds/199#018a3d31-5409-445d-8536-2eda4282c9d6

Same in rules_cc at head: https://buildkite.com/bazel/rules-cc/builds/2156#018a3eb4-14c9-4e9c-a083-831d28ad3698

licenses in rules_proto (but this might be quite old and there are other failures): https://buildkite.com/bazel/rules-proto/builds/1777#018a3ea1-d260-4dc0-9cfd-87d1cb8f5037/115

skylib had failures but was already fixed.

**Comment by comius** [comment]
I’m still seeing an error about sorted dicts in a rule: 

Failed jobs:
- [Buildifier](https://buildkite.com/bazel/google-rules-java-presubmit/builds/200#018a8601-3a9d-4211-839d-67e6883a4e3d)

**Comment by brentleyjones** [comment]
Isn't it because they are using `all`, which includes sorted dicts (which has nothing to do with defaults changing)?

**Comment by comius** [comment]
> Isn't it because they are using `all`, which includes sorted dicts (which has nothing to do with defaults changing)?

Ah, thanks. I didn't know we're doing that.
