### ISSUE TITLE
 fatal error C1083: Cannot open include file: 'google/protobuf/compiler/objectivec/text_format_decode_data.h': 

### ISSUE THREAD

**Issue by sgowroji** [bazelbuild/buildtools#1210]
https://buildkite.com/bazel/bazel-at-head-plus-downstream/builds/3379#018b2723-cda5-4854-b5f3-2b8ba6d896ef

Platform : Windows

Logs:
```
external/com_google_protobuf/src/google/protobuf/compiler/objectivec/text_format_decode_data.cc(31): fatal error C1083: Cannot open include file: 'google/protobuf/compiler/objectivec/text_format_decode_data.h': No such file or directory
(04:15:52) INFO: Elapsed time: 16.801s, Critical Path: 1.21s
(04:15:52) INFO: 653 processes: 291 remote cache hit, 357 internal, 5 local.
(04:15:52) ERROR: Build did NOT complete successfully
//api_proto:api.gen.pb.go_checkshtest                                 NO STATUS
//build:build_test                                                    NO STATUS
//deps_proto:deps.gen.pb.go_checkshtest                               NO STATUS
//extra_actions_base_proto:extra_actions_base.gen.pb.go_checkshtest   NO STATUS
//labels:labels_test                                                  NO STATUS
//lang:tables.gen.go_checkshtest                                      NO STATUS
//tables:tables_test                                                  NO STATUS
//warn:warn_test                                                      NO STATUS
//warn/docs:docs_test                                                 NO STATUS
//wspace:wspace_test                                                  NO STATUS
//build_proto:build.gen.pb.go_checkshtest                       FAILED TO BUILD
Executed 0 out of 11 tests: 1 fails to build and 10 were skipped.
(04:15:52) FAILED:
```

Steps:
```
git clone https://github.com/bazelbuild/buildtools.git 
git reset 72c8ba35684c9bf18d8f33114adab62263673d97 --hard
export USE_BAZEL_VERSION=b3a83a3a3dab0b87952b67cfc7ea8516eabeec4b
bazel test  --enable_runfiles //:tests

```

CC Greenteam  @mai93

**Comment by vladmos** [comment]
In that commit I updated `com_google_protobuf` and also added c++14 flags to `.bazelrc` (which seem to be ignored in the given environment).

Presubmit tests pass on all platforms though, I'm not sure what's the difference with the downstream environment that makes the code fail to build.

**Comment by Wyverald** [comment]
> Presubmit tests pass on all platforms though, I'm not sure what's the difference with the downstream environment that makes the code fail to build.

Presubmit is run with latest release Bazel (at the time, probably 6.4.0), and downstream is run with HEAD bazel.

Auto-sheriff was able to determine that the breakage is from a Bazel change, but the bisect failed with a "No URLs matched" error (https://buildkite.com/bazel/culprit-finder/builds/7851#018bb242-7726-4c79-b122-286304ed4bd7). Did we somehow not build that Bazel commit on Windows?

**Comment by meteorcloudy** [comment]
https://github.com/bazelbuild/bazel/commit/5fb20c39f19063ef4377ba0e66beaed41046d012 is a merge commit accidentally pushed to master, so I guess the publish bazel binaries pipeline didn't get triggered for this. We can manually trigger a build.

**Comment by meteorcloudy** [comment]
Done 
![Screenshot 2023-11-10 at 11 38 51](https://github.com/bazelbuild/buildtools/assets/4171702/c4f2d3f3-223e-4ce7-9bfb-882e9f9ba260)

**Comment by meteorcloudy** [comment]
This is probably a long path issue on windows, as the missing headers are located at paths like:
```
C:\src\tmp\675kvyxq\execroot\com_github_bazelbuild_buildtools/bazel-out/x64_windows-opt-exec-ST-13d3ddad9198/bin/external/com_google_protobuf/src/google/protobuf/compiler/_virtual_includes/command_line_interface/google/protobuf/compiler/command_line_interface.h
```
