### ISSUE TITLE
Sorting issue.

### ISSUE THREAD

**Issue by fhitchen** [bazelbuild/buildtools#125]
Hi,

There don't appear to be any flags to control sorting of list items. When I reformat this entry which is requires exactly this order, buildifier sorts it alphabetically and breaks my C compilation due to the wrong ordering of C header files.

    deps = [":pub",
            ":dst",
            ":shr",
            ":db",
            ":dc",
            ":gn",
            ":ar",
            ":cs",
            ":cm",
            ":po",
            ":oper",
            ":mp",
            ":ms",
            ":sec",
            "//bb/infgn:pub",
            "//bb/infgn:err",
            "//generated_b:lib",
            "//gdd:lib",
            "@oracle_client//:header_files",
            "@qsel//:header_files",
            ],

Looks great, but breaks my compilation. I also know that my code shouldn't be written with duplicate header file names, but that's 20 years of technical debt for you.

    deps = [
        ":ar",
        ":cm",
        ":cs",
        ":db",
        ":dc",
        ":dst",
        ":gn",
        ":mp",
        ":ms",
        ":oper",
        ":po",
        ":pub",
        ":sec",
        ":shr",
        "//bb/infgn:err",
        "//bb/infgn:pub",
        "//gdd:lib",
        "//generated_b:lib",
        "@oracle_client//:header_files",
        "@qsel//:header_files",
    ],

**Comment by pmbethe09** [comment]
Bazel works in a world where the use of fully-qualified '#include' statements removes the brittle nature of import-order, and then allows for sorting of lists like 'hdrs' and 'deps' for readability.

However it appears you can add a comment on the list of "do not sort"
https://github.com/bazelbuild/buildtools/blob/master/build/rewrite.go#L148

although I haven't tried it.

**Comment by fhitchen** [comment]
Thanks, I saw that but could not some how believe that a comment would hack
it. My gigabyte of code exists in a parallel universe where developers took
great delight in cutting and pasting header files willy nilly and left the
makefile as the place where these subtle import orders were hidden.

regards, Francis.

**Comment by pmbethe09** [comment]
The idea is almost always to avoid flags, so everyone just runs 'buildifier', but then to decorate places in the data that need special treatment.

**Comment by pmbethe09** [comment]
WAI, use '# do not sort' in BUILD files.
