### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by limdor** [bazelbuild/buildtools#1252]
Hi, this is not really an issue but a request if it would be possible to create a new release.

The last one is from November 2023 and on January 2024 Windows support was added `https://github.com/bazelbuild/buildtools/pull/1011

It would be cool if a release could be created.

Thanks

**Comment by hunshcn** [comment]
also https://github.com/bazelbuild/buildtools/pull/1244

https://github.com/keith/buildifier-prebuilt/ depends on releases.

**Comment by hunshcn** [comment]
cc @vladmos

**Comment by vladmos** [comment]
Hi,

I'll cut a new release on Monday, there's currently a pending change that changes the order of load statements which affects a lot of internal files, I need to release it isolated from any other changes, and that also requires a large internal cleanup which is already close to be completed. After that I'll merge in other changes and make another release with them.

**Comment by limdor** [comment]
The release has been done, but the windows support does not seem to work unless https://github.com/bazelbuild/buildtools/pull/1262

**Comment by vladmos** [comment]
Just cut a new release that includes #1262
