### ISSUE TITLE
[buildifier] doesn't properly oder `load`-statements

### ISSUE THREAD

**Issue by mgred** [bazelbuild/buildtools#1282]
Buildifier doesn't properly order `load`-statements if there is no newline between the fist statement and a comment string above.

Consider the following example:

_foo.bzl_:
```starlark
# buildifier: disable=module-docstring
load(":baz.bzl", "baz")
load(":bar.bzl", "bar")

print(bar, baz, baz1, bar1)
```

```bash
cat foo.bzl | buildifier -mode=fix -lint=fix
```

The output is:

```starlark
load(":bar.bzl", "bar")

# buildifier: disable=module-docstring
load(":baz.bzl", "baz")

print(bar, baz)
```

This problem can be fixed by inserting a newline between the comment and the following line.

I stumble upon this from time to time and just wanted to know, if this is worth getting fixed. If so, I would like to get my hands on this.

Thanks for any feedback or advice

**Comment by vladmos** [comment]
Compare with the following:

    # baz rule definitions
    load(":baz.bzl", "baz")
    load(":bar.bzl", "bar")

    print(bar, baz, baz1, bar1)

Buildifier doesn't know what the comment describes, it assumes that a comment belongs to the next statement if there are no empty lines between them. Inserting an empty line is the correct workaround.

**Comment by mgred** [comment]
Ok, that makes sense. Thank you :pray:
