### ISSUE TITLE
Remove dependency on io_bazel for build_proto

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/buildtools#143]
I'd like to be able to use the `edit` package in Gazelle, but it transitively depends on `@io_bazel//src/main/protobuf:srcs` via `build_proto`. That's a large download (~95MB) just to copy one proto, and I'd prefer not to pull that in.

How bad would it be to check in a copy of build.proto and maybe have a test (that downstream rules wouldn't depend on) to verify it matches?

Looks like there are a couple other proto files in packages (deps_proto, extra_actions_base_proto) that could use the same treatment.

**Comment by pmbethe09** [comment]
I see, so reference those protos via _test rules, but not in the _library rules to avoid download if not running tests?

**Comment by jayconrod** [comment]
Right, exactly.

I'd be happy with any solution that lets us depend on the `edit` library without download Bazel though.

**Comment by pmbethe09** [comment]
We do have build.gen.pb.go there for pure go users -- so you could apply your own BUILD.bazel file which is just a go_library

**Comment by keith** [comment]
This can be closed by https://github.com/bazelbuild/buildtools/pull/545
