### ISSUE TITLE
Too hard to set up buildifier for a project

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/buildtools#170]
Angular development now requires a buildifier check: https://github.com/angular/angular/blob/ef534c0cc16b4fd3a4c721f814e5530d63cd6642/.circleci/config.yml#L31
Here are notes from setting this up and the problems we are running into
/cc @mhevery

This doesn't work well for a few reasons:
- developers need to install buildifier on their machines, but it needs to match the version of buildifier run on the CI
- when a change is not formatted, it's hard to both fail the CI, and indicate what changes buildifier expects because `--mode=diff` exits 0 even if there's a delta, and it doesn't repeat file names
- windows developers don't have the `find` command indicated here
- developers shouldn't need to think about running buildifier

Here's how I'd like it to work:
- In `WORKSPACE` add a `git_repository` pointing here. The `tag` or `commit` ensures all developers and CI get the same buildifier version.
- Now I can `bazel run @com_github_bazelbuild_buildtools//buildifier` but it uses the runfiles directory, it should `cd` back to the workspace root
- I'd like to have a shorter command for developers, it should be possible to add a simple build rule in my project so I can just `bazel run :buildifier` (similar to how Gazelle is setup)
- The buildifier rule could also have an implicit output so we could `bazel run :buildifier.check` on CI
- `--mode=diff` should exit non-zero if there's a delta, workaround is to run diff followed by check
- `--mode=diff` needs to echo filenames, otherwise you just get anonymous patches like https://circleci.com/gh/angular/angular/26772
- We should document this setup, along with a git pre-commit hook so all changes to BUILD files get fixed without any effort

**Comment by pmbethe09** [comment]
(also in #316) I see you want to operate on files in the current workspace.

https://blog.bazel.build/2018/04/11/bazel-0.12.html
there is a new flag --direct_run plus environment variables in that post for doing as you want

**Comment by alexeagle** [comment]
I think these have been mostly fixed since buildifier has a binary release, our projects can fetch that binary from NPM, and the exit codes let us enforce it on CI
