### ISSUE TITLE
buildozer: add "substitute" command

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/buildtools#182]
### Proposal

Buildozer should support a new command, `substitute`, which would let users replace labels in a specific attribute that match a label with wildcards. This would be useful for updating build files after a package is moved.

```
substitute <attr> <from_label> <to_label>
```

### Example

Suppose we want move a large set of packages from our source tree to our test tree. We need to update  tests that depend on libraries that were moved. We could do this with `replace`, but that requires one `replace` command per moved rule, so this may be inconvenient.

```
$ git mv java/com/example/testutils javatests/com/example/testutils
$ buildozer substitute deps //java/com/example/testutils/... //javatests/com/example/testutils/... //javatests/...:%java_test
```

This command modifies the `deps` attribute of all `java_test` rules in `//javatests/...`. It replaces any label that starts with `//java/com/example/testutils` with a label that starts with `//javatests/com/example/testutils` instead.

```
java_test(
    name = "foo_test",
    ...
    deps = [
-        "//java/com/example/testutils/bar",
+        "//javatests/com/example/testutils/bar",
    ],
```

### Use case

This was originally proposed for Gazelle for use in Kuberentes (see bazelbuild/bazel-gazelle#63). However, it seems like this would be generally useful to have in Buildozer.

Kubernetes' use case is vendoring. They need to be able to copy the contents of an external repository that already has BUILD files into a subdirectory of one of their repositories. There should be an easy (automatic) way to get the BUILD files to make sense again. They could do something like this:

```
$ buildozer substitute * //... //vendor/github.com/bazelbuild/buildtools/... //vendor/github.com/bazelbuild/buildtools/...
```

**Comment by jayconrod** [comment]
cc @ixdy @pmbethe09

**Comment by pmbethe09** [comment]
This definitely seems like a useful feature.  Do you have time to code this Jay or are you looking for volunteers?

**Comment by jayconrod** [comment]
I can work on this, probably next week. Just wanted to confirm the user interface made sense before starting.

**Comment by laurentlb** [comment]
> that match a label with wildcards

I'm wondering if we should use regex for this.

**Comment by jayconrod** [comment]
Regex would be more powerful, probably easier to implement. I think it's mostly a question of UX. If regex isn't too surprising in this context, I'm happy to do it.
