### ISSUE TITLE
unused_deps doesn't support BUILD.bazel files

### ISSUE THREAD

**Issue by uppi** [bazelbuild/buildtools#204]
According to https://github.com/bazelbuild/bazel/issues/552, `BUILD.bazel` is a valid name for BUILD file, but `unused_deps` called on the target with `BUILD.bazel` file tries to open `BUILD` and fails:

```
2018/02/08 19:00:32 open /some/path/BUILD: no such file or directory when parsing /some/path/BUILD
```

**Comment by pmbethe09** [comment]
Seems to be from InterpretLabelForWorkspaceLocation in edit/edit.go
