### ISSUE TITLE
Diff mode doesn't include the file that needs updating

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/buildtools#220]
Atleast in the last released version (0.6.0), diff mode doesn't say what file the diff is for, that isn't very useful when it is checking multiple files at once.

**Comment by thomasvl** [comment]
Still a problem in 0.11.1.

**Comment by pmbethe09** [comment]
Will this break any existing tooling?

**Comment by thomasvl** [comment]
Nothing I've written. Since there are no file markers, if you pass multiple files, you have no way to know what the diffs apply to, so I can't really see how someone could have automated it with multiple files.

The one case they could automate is single file mode, because then you know what the diffs apply to.  So if you don't want to break any tooling that does that, don't print the file header if invoked on a single file.

**Comment by thomasvl** [comment]
Still and issue in 0.19.2

**Comment by thomasvl** [comment]
0.22.0 does seem to be fixed
