### ISSUE TITLE
Release binaries don't know they are releases

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/buildtools#275]
Atleast on macOS, downloaded the 0.11.1 release:

```
$ ./buildifier --version
buildifier version: redacted 
buildifier scm revision: redacted 
```

**Comment by pmbethe09** [comment]
my fault -- I forgot to add --workspace_status_command=$PWD/status.sh to my bazel build command.

Rebuilt and fixed now for that release -- I note that buildozer and buildifier do not have a -version flag...
