### ISSUE TITLE
shift/reduce conflicts

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/buildtools#280]
As of recent grammar changes for skylark we now get

`conflicts: 58 shift/reduce`

when running: go tool yacc

Worth investigating.

**Comment by vladmos** [comment]
With #335 there are only 20 conlficts remaining.

**Comment by pmbethe09** [comment]
nice.  presumably the remaining are dangling-else issues which might get cleaned up by using 
`%prec ShiftInstead` to affirm the preference for shift over reduce.

https://en.wikipedia.org/wiki/Dangling_else

**Comment by drigz** [comment]
If this is not trivial to fix, is there a way to suppress the message so that it's not seen when `buildtools` is pulled in as an external repository?

**Comment by jayconrod** [comment]
Gazelle updated to buildtools 3.2.1, and I've started seeing these warnings on every build:

```
INFO: From Action external/com_github_bazelbuild_buildtools/build/parse.y.baz.go:
rule exprs:  expr  never reduced
rule exprs:  exprs ',' expr  never reduced
rule exprs_opt:   never reduced
rule exprs_opt:  exprs comma_opt  never reduced
4 rules never reduced

conflicts: 24 shift/reduce
```

Any chance these can be fixed? It sounds like these aren't new, but IME shift / reduce conflicts in a yacc grammar are a good indication of bugs. If they really aren't a problem, do they need to be printed?

**Comment by jayconrod** [comment]
Gentle ping...

It looks like these messages were silenced in #430 by piping stdout to `/dev/null`. However #841 switched from using a `genrule` to calling `goyacc` directly, so now these messages are printed again.

These show up every time Gazelle is built or run, even when the action is cached, so it's pretty annoying.

**Comment by vladmos** [comment]
I'll take a look. It seems that the default behavior (to resolve shift/reduce conflicts always as shift) is correct in these cases, but I can make the grammar less ambiguous by adding `%prec ShiftInstead` to the conflicting rules.

**Comment by jayconrod** [comment]
Thanks for fixing this! I've updated Gazelle to the latest commit and can confirm these messages aren't showing up anymore.
