### ISSUE TITLE
buildifier's use of "linkstamp" doesn't work any more in rules_go 0.12

### ISSUE THREAD

**Issue by jmillikin-stripe** [bazelbuild/buildtools#322]
In [buildtools/buildifier/BUILD.bazel](https://github.com/bazelbuild/buildtools/blob/49d4d323a22b7ae09d6c5ecd3a1f7693c0cf2dc1/buildifier/BUILD.bazel):
```
go_binary(
    name = "buildifier",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
    linkstamp = "main",
)
```

The `linkstamp` attribute is breaking the build with the current version of rules_go, 0.12, because `go_binary.linkstamp` was removed in favor of `go_library.x_defs`.

**Comment by pmbethe09** [comment]
@jayconrod  - can you help?
