### ISSUE TITLE
bzlint

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/buildtools#341]
We have a plan to create a new tool, called `bzlint`. It should act as a linter and a code fixer.

`bzlint tools/*.bzl` reports warnings in the bzl files
`bzlint --fix tools/*.bzl` applies fixes to bzl files

An example of fix is to remove unused load() arguments, but we can expect many other fixes.

**Comment by philipjameson** [comment]
What's the rationale for not integrating this into buildifier? It seems less than ideal to have to have multiple tools to lint build-related files. Also, is there ongoing design somewhere for this?

**Comment by laurentlb** [comment]
Good question.
We could have `buildifier --warn` and `buildifier --fix` (by default, buildifier should only reformat the file, not apply the possibly unsafe changes). What do you think, Vlad?

**Comment by vladmos** [comment]
Bzlint is available as a part of buildifier: https://github.com/bazelbuild/buildtools/tree/master/buildifier#linter

**Comment by laurentlb** [comment]
... and thanks Philip for the suggestion!
It's probably simpler for users to have a single binary
