### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by HowJMay** [bazelbuild/buildtools#348]
OS: Ubuntu 16.06 LTS

I used command 'bazel build //buildifier' in folder buildtools/buildifier. 
however, when I ran 'buildifier.bash' in buildtools/bazel-bin, there is an error 
'./buildifier.bash: line 8: : command not found'
 How to solve this problem?

**Comment by pmbethe09** [comment]
this seems more like a question for stackoverflow

when you run 'bazel build //buildifier' as successful build prints the location of the executable.  On linux
bazel-bin/buildifier/linux_amd64_stripped/buildifier

not sure why you were expecting a 'buildifier.bash' file
