### ISSUE TITLE
Update go_rules, bazel CI red

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/buildtools#353]
Howdy dear buildtools owners,

It seems that bazel's CI is red for buildtools: https://buildkite.com/bazel/bazel-with-downstream-projects-bazel/builds/386#175defe4-18a1-42d2-bce3-7aa09f3efacf. I blame it to not using the most recent rules_go version, which contains the fix (https://github.com/bazelbuild/rules_go/commit/24c4ae8023aa8d92d3b67a4fd968f49b99225230). I believe updating the rules_go version will fix the CI. Thanks!

**Comment by laurentlb** [comment]
Should be fixed with https://github.com/bazelbuild/buildtools/pull/354
(please reopen if it still fails)

**Comment by mhlopko** [comment]
Thanks! :)
