### ISSUE TITLE
Buildozer ignores command line command/label-list when -f is provided

### ISSUE THREAD

**Issue by endobson** [bazelbuild/buildtools#357]
Buildozer documents its usage as
```
buildozer [OPTIONS] ['command args' | -f FILE ] label-list
```

Thus `command args` and `-f FILE` are supposed to be mutually exclusive, but this isn't enforced. In addition `label-list` is ignored if `-f FILE` is provided.

I believe the intended usage is
```
buildozer [OPTIONS] ['command args' label-list | -f FILE ]
```

Example command which does nothing right now, but should likely do something different (either error or apply the command).
```
buildozer -f /dev/null 'add dep //foo:bar' //libraries:io
```

**Comment by aiuto** [comment]
+100  The current behavior is almost entirely useless. 
You should be able to have a list of commands in the command file - with NO target label, and apply them
to all the labels specified on the command line.

**Comment by aiuto** [comment]
#991 solves the problem for me.  It needs tests and a doc fix, but I am using it for now to complete a large change.
