### ISSUE TITLE
Support unused import removal with Buildifier

### ISSUE THREAD

**Issue by psimmons-vistar** [bazelbuild/buildtools#379]
It would be nice if Buildifier could support detecting and removing unused load statement imports.

Would definitely be willing to work on this if I could be given some guidance on if this makes conceptual sense in Buildifier, and where in the code a modification like this would happen.

**Comment by laurentlb** [comment]
Agree. This is blocked on this Bazel change: https://github.com/bazelbuild/bazel/issues/5636
After that, it will be safe to remove those.

**Comment by psimmons-vistar** [comment]
Sweet, I was wondering if it would've made more sense in buildozer.  Thanks

**Comment by mboes** [comment]
But AFAIK, buildozer only works on BUILD files, not Starlark files, right? How do I detect and remove unused imports in Starlark files?

**Comment by vladmos** [comment]
You can use buildifier:

    $ buildifier --lint=fix --warnings=load your/file.bzl

**Comment by thundergolfer** [comment]
@vladmos That command didn't do anything for me (version `0.29.0`). This works though: 

`buildozer 'fix unusedLoads' //...:*`

**Comment by vladmos** [comment]
That's weird, could you please share a file that's not being fixed with buildifier?
