### ISSUE TITLE
Buildtools buildkite presubmit not setup

### ISSUE THREAD

**Issue by mhlopko** [bazelbuild/buildtools#382]
Hello,

To make sure failures like https://github.com/bazelbuild/buildtools/issues/381
don't happen again, can you setup buildkite presubmit for this project? Bazel devprod team should be able to help with that.

Thanks! :)

**Comment by pmbethe09** [comment]
I thought we already had that?  Or at least in the pass we had some sort of presubmit, but maybe that didn't get persisted when moving to buildkite?

**Comment by laurentlb** [comment]
cc @philwo 

We had tests running in https://github.com/bazelbuild/buildtools/pull/376 but not https://github.com/bazelbuild/buildtools/pull/377 or https://github.com/bazelbuild/buildtools/pull/378.

**Comment by vladmos** [comment]
There are tests for #377: https://buildkite.com/bazel/buildtools/builds/399 and #378: https://buildkite.com/bazel/buildtools/builds/403

**Comment by vladmos** [comment]
I suggest we set up mandatory presubmit checks for pull requests (I don't see how to do it, probably don't have enough permissions).

**Comment by philwo** [comment]
@laurentlb You did have presubmit checks running for https://github.com/bazelbuild/buildtools/pull/377 and https://github.com/bazelbuild/buildtools/pull/378. For 377 they passed and for 378 they're stuck an "Waiting for a project member to verify this pull request.". You have to click "View details" on already submitted PRs to see them though.

<img width="817" alt="screenshot 2018-10-04 at 11 27 04" src="https://user-images.githubusercontent.com/504652/46465282-84312500-c7c8-11e8-9a12-e5394bfefe61.png">

If you want, I can enable mandatory passing presubmit checks for merging to the master branch for this repo.

**Comment by laurentlb** [comment]
Thanks @philwo!
I think mandatory checks would make sense.

**Comment by philwo** [comment]
I changed the GitHub branch protection rules to look like this now. LGTY? Any changes, just let me know or @laurentlb should also be able to change the settings as he's an admin on the repo.

<img width="703" alt="screenshot 2018-10-08 at 17 38 07" src="https://user-images.githubusercontent.com/504652/46635025-03a05a80-cb21-11e8-817e-051d459c83e2.png">
<img width="713" alt="screenshot 2018-10-08 at 17 38 11" src="https://user-images.githubusercontent.com/504652/46635028-04d18780-cb21-11e8-84ba-22a104d986d3.png">
<img width="717" alt="screenshot 2018-10-08 at 17 38 16" src="https://user-images.githubusercontent.com/504652/46635029-0602b480-cb21-11e8-94a1-59e72ce3546d.png">

**Comment by laurentlb** [comment]
Thanks!
That should be fine (if not, I'll take a look).

**Comment by vladmos** [comment]
FYI: I can't merge pull requests anymore, probably because I'm not an administrator.

**Comment by laurentlb** [comment]
You have write access, do you know why it's not enough?

**Comment by philwo** [comment]
@vladmos Can you give a link to a PR that you think you should be able to merge, but can’t? Let’s see what GitHub thinks is blocking you.

**Comment by vladmos** [comment]
https://github.com/bazelbuild/buildtools/pull/390, but it's been merged already.

The error message was saying that I don't belong to a group of users who're allowed to merge, and your screenshot shows that this group is limited to the organisation and repo administrators, which I'm not.

**Comment by philwo** [comment]
The config says to restrict *pushing* to these branches, which is actually what we want (all changes have to go through a PR and then be merged).

Please ping me when you have another still open PR where this happens and we can have a look and try out different settings.

**Comment by vladmos** [comment]
Another example: https://github.com/bazelbuild/buildtools/pull/391. It's been approved, the tests have passed, but it reads "You’re not authorized to merge this pull request."

**Comment by philwo** [comment]
I've disabled "Restrict who can push to matching branches" - does it work now for you? :)

**Comment by vladmos** [comment]
Yes, thanks!
