### ISSUE TITLE
Create buildozer rule runnable through bazel

### ISSUE THREAD

**Issue by keith** [bazelbuild/buildtools#387]
The buildifier command has a [great way](https://github.com/bazelbuild/buildtools/tree/master/buildifier#setup-and-usage-via-bazel) to run it through bazel, which gives you the advantage of having all of its dependencies managed, instead of having to ask users to install it themselves. We should add something similar for buildozer where consumers can provide some default arguments like `fix unusedLoads` or other common tasks, so that they can be run directly through bazel

**Comment by ash2k** [comment]
See https://github.com/bazelbuild/buildtools/pull/326

**Comment by keith** [comment]
Ah I didn't realize that you could run the binary directly with:

```
./bazelw run --run_under="cd $PWD && " @com_github_bazelbuild_buildtools//buildozer -- whatever
```

I think the rule is nice, but for our use case this is probably good enough
