### ISSUE TITLE
unused_deps not working

### ISSUE THREAD

**Issue by mkilpatrick** [bazelbuild/buildtools#396]
unused_deps stopped working for us about 6 months ago. When we run it, it tries to open files that don't exist. 

```
mkilpatrick-mpro:alpha mkilpatrick$ unused_deps src/com/yext/bulk/common/...
2018/10/15 11:43:37 running: bazel query --tool_tag=unused_deps --keep_going --color=yes --curses=yes kind('(java|android)_*', src/com/yext/bulk/common/...)
2018/10/15 11:43:37 running: bazel build --tool_tag=unused_deps --keep_going --color=yes --curses=yes src/com/yext/bulk/common/...
Using remote cache (va). Disable by setting BAZEL_NO_CACHE=1
WARNING: Option 'experimental_remote_spawn_cache' is deprecated
INFO: Analysed 57 targets (0 packages loaded).
INFO: Found 57 targets...
INFO: Elapsed time: 0.780s, Critical Path: 0.01s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action

2018/10/15 11:43:39 open /private/var/tmp/_bazel_mkilpatrick/ecc7778653efb77408ccae0a11894b62/execroot/yext/bazel-out/darwin-fastbuild/bin/src/com/yext/bulk/common/fieldnames/fieldidentifier/canonicalizer/canonicalizer.jar-2.params: no such file or directory
2018/10/15 11:43:39 open /private/var/tmp/_bazel_mkilpatrick/ecc7778653efb77408ccae0a11894b62/execroot/yext/bazel-out/darwin-fastbuild/bin/src/com/yext/bulk/common/fieldnames/fieldidentifier/uuid/uuid.jar-2.params: no such file or directory
2018/10/15 11:43:39 open /private/var/tmp/_bazel_mkilpatrick/ecc7778653efb77408ccae0a11894b62/execroot/yext/bazel-out/darwin-fastbuild/bin/src/com/yext/bulk/common/fieldnames/fielddefinition/profilefieldnode/profilefieldnode.jar-2.params: no such file or directory
2018/10/15 11:43:39 no deps attribute for protobuf in /Users/mkilpatrick/alpha/src/com/yext/bulk/common/fieldnames/fieldidentifier/BUILD
2018/10/15 11:43:39 open /private/var/tmp/_bazel_mkilpatrick/ecc7778653efb77408ccae0a11894b62/execroot/yext/bazel-out/darwin-fastbuild/bin/src/com/yext/bulk/common/fieldnames/fieldidentifier/protobuf_compile_imports.jar-2.params: no such file or directory
2018/10/15 11:43:39 open /private/var/tmp/_bazel_mkilpatrick/ecc7778653efb77408ccae0a11894b62/execroot/yext/bazel-out/darwin-fastbuild/bin/src/com/yext/bulk/common/fieldnames/fieldidentifier/protobuf_compile_imports.jdeps: no such file or directory
2018/10/15 11:43:39 protobuf_compile_imports not found in /Users/mkilpatrick/alpha/src/com/yext/bulk/common/fieldnames/fieldidentifier/BUILD
2018/10/15 11:43:39 no deps attribute for protobuf in /Users/mkilpatrick/alpha/src/com/yext/bulk/common/subfield/BUILD
2018/10/15 11:43:39 open /private/var/tmp/_bazel_mkilpatrick/ecc7778653efb77408ccae0a11894b62/execroot/yext/bazel-out/darwin-fastbuild/bin/src/com/yext/bulk/common/subfield/protobuf_compile_imports.jar-2.params: no such file or directory
2018/10/15 11:43:39 open /private/var/tmp/_bazel_mkilpatrick/ecc7778653efb77408ccae0a11894b62/execroot/yext/bazel-out/darwin-fastbuild/bin/src/com/yext/bulk/common/subfield/protobuf_compile_imports.jdeps: no such file or directory
2018/10/15 11:43:39 protobuf_compile_imports not found in /Users/mkilpatrick/alpha/src/com/yext/bulk/common/subfield/BUILD
2018/10/15 11:43:39 no deps attribute for protobuf in /Users/mkilpatrick/alpha/src/com/yext/bulk/common/BUILD
2018/10/15 11:43:39 open /private/var/tmp/_bazel_mkilpatrick/ecc7778653efb77408ccae0a11894b62/execroot/yext/bazel-out/darwin-fastbuild/bin/src/com/yext/bulk/common/protobuf_compile_imports.jar-2.params: no such file or directory
2018/10/15 11:43:39 open /private/var/tmp/_bazel_mkilpatrick/ecc7778653efb77408ccae0a11894b62/execroot/yext/bazel-out/darwin-fastbuild/bin/src/com/yext/bulk/common/protobuf_compile_imports.jdeps: no such file or directory
2018/10/15 11:43:39 protobuf_compile_imports not found in /Users/mkilpatrick/alpha/src/com/yext/bulk/common/BUILD
No unused deps found.
```

**Comment by mkilpatrick** [comment]
This is using bazel version 0.17.2

**Comment by pmbethe09** [comment]
I thought that 
https://github.com/bazelbuild/buildtools/commit/c2e57403a1338bef9a8b4376396d252cb801eab1
should have fixed unused_deps.

This is bazel 0.17.2 and buildtools ~ HEAD?

**Comment by mkilpatrick** [comment]
I realized buildtools was not at HEAD, but I just updated and still get the same errors.

**Comment by mkilpatrick** [comment]
Is anything else needed from me on this issue? I'd like to use it to run against a large repo. My last try was using commit 220349f891794f407450d6eada3a2cddf370040a.

**Comment by pmbethe09** [comment]
@brown -- any ideas, you helped us fix this last time...

**Comment by brown** [comment]
I got unused_deps working with Bazel 0.15.0 about 4 months ago.  I've just upgraded
Bazel to 0.18.0, but haven't yet had a chance to test unused_deps with it.  I'll try it out
tomorrow and see if it works for me.

Note that unused_deps is not perfect in its current form.  It has some problems with aliases,
occasionally says a dependency is unused when it's not, etc.  Getting it to work perfectly
may require more support from Bazel.

**Comment by brown** [comment]
I built unused_deps at d0dd07283df5fbf198a7aff0b7838980d171551b today and ran it on
several java_library targets that I had just compiled with Bazel 0.18.0.  It worked fine.

Please give an exact recipe for a situation where unused_deps fails.

**Comment by haikalpribadi** [comment]
Hi everyone,

We also find that `unused_deps` is not working at all. We use the latest versions: `bazel 0.19.0` and `buildtools 0.17.2`.

I've pushed our code to [`haikalpribadi/grakn` branch `unused-deps-not-working`](https://github.com/haikalpribadi/grakn/tree/unused-deps-not-working), which you can clone and run:
```
bazel build //client-java:all
bazel run //dependencies/tools:unused-deps -- //client-java
```

You will find that `unused_deps` returns: `No unused deps found.`

Meanwhile, we know for a fact that the following dependencies of `//client-java:client-java` are no longer needed (and we have confirmed by removing them afterwards).
```
//dependencies/maven/artifacts/com/codahale/metrics:metrics-core
//dependencies/maven/artifacts/com/github/rholder:guava-retrying
//dependencies/maven/artifacts/com/netflix/hystrix:hystrix-core
//dependencies/maven/artifacts/com/sun/jersey:jersey-client
//dependencies/maven/artifacts/io/reactivex:rxjava
//dependencies/maven/artifacts/javax/ws/rs:jsr311-api
//dependencies/maven/artifacts/org/sharegov:mjson
```

cc: @vmax is there anything we can do to help debug this issue?

**Comment by cushon** [comment]
This is the change to params files that broke the assumptions unused_deps is making: https://groups.google.com/d/msg/bazel-discuss/oMguVWL-Ckg/AiFvCSkfBgAJ

**Comment by cushon** [comment]
I have a fix: #420

**Comment by mkilpatrick** [comment]
The above fix is working for me.

**Comment by haikalpribadi** [comment]
Is it possible to make a new release `bazelbuild/buildtools` @cushon ? The way we've integrated `unused_deps` at the moment is by using `http_file` and it won't necessarily work with `git_repository` at the moment. :/ 

Thank you so much for the fix! Looking forward to start using `unused_deps`!

**Comment by cushon** [comment]
I don't know how or when releases happen. Maybe @pmbethe09 does?

**Comment by pmbethe09** [comment]
They have been totally manual by me.  I can try and cut one tomorrow.

**Comment by haikalpribadi** [comment]
Nice. Sounds like tomorrow's release will come with diamonds, @pmbethe09 ;)

**Comment by pmbethe09** [comment]
https://github.com/bazelbuild/buildtools/releases/tag/0.19.2
