### ISSUE TITLE
unused_deps not detecting unused dependencies at all

### ISSUE THREAD

**Issue by haikalpribadi** [bazelbuild/buildtools#441]
Hi everyone,

I'm so sorry for posting this again, right after @pmbethe09 closes issue #396. But I've upgraded `unused_deps` to the latest release, `0.19.2` today, and `unused_deps` is still not detecting any unused dependencies.

You can find our code at [`haikalpribadi/grakn` branch `unused-deps-not-working`](https://github.com/haikalpribadi/grakn/tree/unused-deps-not-working), which you can clone and run:
```
bazel build //client-java:all
bazel run //dependencies/tools:unused-deps -- //client-java
```

You will find that `unused_deps` returns: `No unused deps found.`

Meanwhile, we know for a fact that the following dependencies of `//client-java:client-java` are no longer needed (and we have confirmed by removing them afterwards).
```
//dependencies/maven/artifacts/com/codahale/metrics:metrics-core
//dependencies/maven/artifacts/com/github/rholder:guava-retrying
//dependencies/maven/artifacts/com/netflix/hystrix:hystrix-core
//dependencies/maven/artifacts/com/sun/jersey:jersey-client
//dependencies/maven/artifacts/io/reactivex:rxjava
//dependencies/maven/artifacts/javax/ws/rs:jsr311-api
//dependencies/maven/artifacts/org/sharegov:mjson
```

Can someone help us look into this?

**Comment by pmbethe09** [comment]
I can repeat your experience using bazel 0.19.2

Could it be unused_deps not working for java_library that are actually exports of something else?

Will test a simpler example and see.

**Comment by vmax** [comment]
Can confirm it doesn't work for `bazel 0.29.0` and `unused_deps 0.29.0` still

**Comment by pmbethe09** [comment]
@vladmos @laurentlb -- if we want to continue to provide unused_deps, probably have to fix it for whatever the latest .jdeps file changes are
