### ISSUE TITLE
Do not reformat with --lint=warn

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/buildtools#453]
```bash
$ echo 'x=1' > /tmp/BUILD

$ buildifier --lint=warn /tmp/BUILD
/tmp/BUILD:1: unused-variable: Variable "x" is unused. Please remove it.
To disable the warning, add '@unused' in a comment. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#unused-variable)

$ cat /tmp/BUILD
x = 1
```

When used as a linter, buildifier shouldn't modify the files.

**Comment by keith** [comment]
I think this is related to the fact that right now you can't run a non-fix buildifier mode with lint=warn. We would also like this behavior. Currently on CI we run this rule:

```python
buildifier(
    name = "buildifier.diff",
    mode = "diff",
)
```

And we'd like to start running it with the linter as well:

```python
buildifier(
    name = "buildifier.diff",
    lint_mode = "warn",
    mode = "diff",
)
```

In this case we get [this failure](https://github.com/bazelbuild/buildtools/blob/3f6a2256863cb60d56b63b883dc797225b888e15/buildifier/buildifier.go#L150-L154 though:

```
buildifier: lint mode warn is only compatible with --mode=fix
```

I can't tell exactly why this restriction exists, but it would be nice to lift for this CI use case

**Comment by vladmos** [comment]
Perhaps we should change the flags, e.g. remove the `--lint` flag and add `warn` and `lint` as new values for the `--mode` flag (not sure if `lint` is a good value for applying the fixes, but `--mode=fix` is already reserved for formatting). What do you think?

**Comment by keith** [comment]
So in todays terminology these would be equal:

--mode=lint == --mode=fix && --lint=fix
--mode=fix == --mode=fix && --lint=off
--mode=warn == --mode=warn && --lint=warn

? How does `diff` fit into this?

**Comment by manekinekko** [comment]
Hi, is it possible to just output the lint warnings without applying any auto-fix?

**Comment by keith** [comment]
On our CI because of this we're running 2 jobs, 1 that runs with `-mode=diff` and no lint, and one with `-mode=fix` and `-lint=warn`

**Comment by manekinekko** [comment]
does the `-mode=diff` detect both formatting and linting errors?

**Comment by manekinekko** [comment]
Interesting. Thanks for the feedback.

**Comment by vladmos** [comment]
Sorry, the issue got lost in my backlog.

I think it makes sense to not require `--mode=fix` if `--lint=warn` is provided. This way `--lint=warn` can be combined with any mode (check, fix, diff, print_if_changed). Providing `--lint=fix` will still require `--mode=fix` (which is default).

Will that be suitable for your usecases?

**Comment by thomasvl** [comment]
If you do `--mode=fix` and `--lint=warn` can't the file line references for the warnings be wrong because the `fix` could wrap things, add/remove lines, etc.?  It seems like `--mode=none` or `--mode=diff` would make more sense with `--lint=warn` so the output will be correct for tools to pick up as results for IDEs, etc.

**Comment by vladmos** [comment]
It can, but that's how it works now (currently `--lint=warn` doesn't work with any other value for `--mode` than `fix`).

Perhaps it makes sense to default the `--mode` value to `check` if it's not provided explicitly and `--lint=warn` is provided, but that would be a breaking change. Removing the restriction on `--mode` with `--lint=warn` on the other hand won't break users and is a simple thing to implement.
