### ISSUE TITLE
buildifier spuriously warns about non-keyword arguments to register_toolchains()

### ISSUE THREAD

**Issue by mboes** [bazelbuild/buildtools#454]
Given the following snippet:

```python
# WORKSPACE file
register_toolchains(
  "//foo",
  "//bar",
)
```

Buildifier says:

```
WORKSPACE:2: positional-args: All calls to rules or macros should pass arguments by keyword (arg_name=value) syntax. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#positional-args)
```

But register_toolchains() is a variadic function with no keyword arguments. So buildifier should not produce any warning for the above code.

**Comment by ttsugriy** [comment]
buildifier has a list of hard-coded functions that [use positional arguments](https://github.com/bazelbuild/buildtools/blob/3f6a2256863cb60d56b63b883dc797225b888e15/warn/warn.go#L35-L41) which can be extended to support `register_toolchains` although I'm not sure how scalable it is to maintain a hard-coded list of functions...
