### ISSUE TITLE
--lint=warn should have non-zero exit code when there are warnings

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/buildtools#470]
I want to configure my CI to prevent contributors from adding code that has bazel lint warnings.

Currently `buildifier --lint=warn` exits zero whether or not there are warnings. That makes it impossible to get a red build when a PR introduces a lint warning.

**Comment by keith** [comment]
I believe I fixed this on master https://github.com/bazelbuild/buildtools/pull/460 if you are still seeing issues let me know!

**Comment by alexeagle** [comment]
I see, it's just not released yet
https://github.com/bazelbuild/buildtools/compare/0.19.2.1...master

Thanks!!
