### ISSUE TITLE
`--path` doesn't work with `--lint` and using stdin/stdout

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/buildtools#475]
looks like the problem is https://github.com/bazelbuild/buildtools/blob/master/buildifier/buildifier.go#L317-L330, the `--path` arg doesn't taken into account until after the lint run.  It the override is applied first and lint honored the override instead of `filename` it might all "just work".

**Comment by jhahn21** [comment]
I think it's a bug.
Can we just pass `-path` value instead of an empty string to `filename`?

**Comment by dbarnett** [comment]
Permalink to the code should have been https://github.com/bazelbuild/buildtools/blob/d77ccdb79b6e93527a14305048d2657f6b3ba5fa/buildifier/buildifier.go#L317-L330, for anyone else confused about why it takes you to seemingly unrelated code now.
