### ISSUE TITLE
unsorted-dict-items doesn't look so great with `select()` usage

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/buildtools#480]
Since a [`select()`](https://docs.bazel.build/versions/master/be/functions.html#select) takes a dictionary, we're forcing those mappings to be sorted.  But it is pretty common to have a `//conditions:default` in there, and having that sorted in with the other things isn't so great, seems like that should still always be the last entry.

**Comment by thomasvl** [comment]
@ttsugriy @vladmos fyi

**Comment by ttsugriy** [comment]
in my experience maintaining conventions for ordering has many issues - from extra burden on engineers to cargo cult, where people start to believe that certain order is actually required for things to work, but if it's a big issue, I can shoot a PR to ignore dictionary literals passed to `select`. It's also possible to disable this warning by adding `# @unsorted-dict-items` comment as mentioned in a [warnings section](https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#dictionary-items-should-be-ordered-by-their-keys). Please let me know what you think.

**Comment by thomasvl** [comment]
I generally like the idea of the sorting, the `select()` is just a case where the `//conditions:default` is like a final `else` so having it at the end makes the most sense to me.  When it is mixed in with the other values it can be hard to notice.

**Comment by thomasvl** [comment]
aside: all the other things that can be disabled seem to use `# buildozer: disable=NAME`, why is this one different?

**Comment by ttsugriy** [comment]
for specific values, it's also possible to use priorities defined in tables.json. Is it always `//conditions:default` or there are many "default"-like values that should be taken care of?

**Comment by laurentlb** [comment]
Given that there are many corner cases, I wonder if it's a good idea to sort by default. What do you think of sorting only if there's a "keep-sorted" comment?

(I don't think other code formatters try to sort items)

**Comment by ttsugriy** [comment]
I have reformatted all build and .bzl files at fb and there was no single concern raised about any edge cases, but if it does not work as well for others, I can totally add some config option to control the default behavior, so that we can keep it on for everything :) Would this work?

**Comment by laurentlb** [comment]
Thanks, that's a useful data point! We should be able to keep enabled then :)

**Comment by ttsugriy** [comment]
@thomasvl, in such case it seems like we can just add something like
```
"//conditions:default": 100
```
to https://github.com/bazelbuild/buildtools/blob/ab1d6a0ca532b7b7f3450a42d5cbcfdcd736fd41/tables/tables.go#L201

it's also possible to do it via `tables.json` config file. I'll write a test to confirm...

**Comment by ttsugriy** [comment]
@thomasvl, I've shared https://github.com/bazelbuild/buildtools/pull/481 to address the default condition. Is there anything else that should be taken care of? Btw, thank you for bringing this up!

**Comment by thomasvl** [comment]
Thanks.  Most of what I'm reformatting has been looking good, the `select()` was the one thing that really stuck out since I'm so used to defaults being at the end (and that's what the docs even do).

**Comment by thomasvl** [comment]
Fixed by #481
