### ISSUE TITLE
Using buildifier in bazel is incompatible with 0.21

### ISSUE THREAD

**Issue by keith** [bazelbuild/buildtools#490]
Because of the `REPOSITORY_NAME` -> `repository_name()` change, you currently have to set `--incompatible_package_name_is_a_function=false` in your bazelrc if you'd like to use buildifier from within bazel.

I have fixed this in this PR https://github.com/bazelbuild/bazel/pull/6782/ if someone can encourage an owner to review and merge that would be great.

**Comment by Profpatsch** [comment]
The PR was merged, close?
