### ISSUE TITLE
FR: Disabling warnings with `--warnings`

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/buildtools#493]
Currently `--warnings=` requires the completely list of warning one wants to enable, but as more warning are added, that means someone using this to skip a few tests ends up freezing the set of validations and doesn't pick up new ones.

It would be nice if there was a way to exclude warnings instead, say similar to how bazel has some targets that can take `-` prefixed targets/tags in some case to subtrack out things.  So say something like `--warnings=-out-of-order-load,-unsorted-dict-items` to get the default (`all`), except for those two warnings.

**Comment by vladmos** [comment]
Good idea, however perhaps only one minus sign should be requred, egg `--warnings=-foo,bar`, which means all warnings except `foo` and `bar` should be shown.

In the future if you want the semantics "exclude `foo` but include `bar` which is not default" you'll be able to use, for example, `--warnings=-foo,+bar`.

**Comment by thomasvl** [comment]
While that might work, it likely makes sense to stay consistent with bazel.  Looking at https://docs.bazel.build/versions/master/command-line-reference.html, it seems the repeated minus signs are needed.

I'd also be worried something like `--warnings=-foo,bar,baz` becoming error prone.  You go to enable `bar`, so you delete that part.  You go to enable `foo` and an accidentally delete the `-` also suddenly changing the meaning significantly.
