### ISSUE TITLE
Confirming the buildifier behavior of out-of-order-load checks.

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/buildtools#501]
The behavior here might just be what we're stuck with since it likely matches what has been done with BUILD files for labels on other attributes (`deps`, etc.), but when looking at load statements, a _pure_ lexicographical ordering seems odd.

Sending:
```
"""Module comment."""

load("//foo:xyz.bzl", "xyz")
load("//foo/bar:mno.bzl", "mno")

def something():
    xyz.do()
    mno.do()
    return True
```

Through `buildifier --lint=fix` reorder the `load()` calls:

```
"""Module comment."""

load("//foo/bar:mno.bzl", "mno")
load("//foo:xyz.bzl", "xyz")

def something():
    xyz.do()
    mno.do()
    return True
```

While ":" > "/", this feels sorta wrong.  It seems like all the `load()`s from _//foo_ should get listed before the ones from _//foo/bar_ since this is down a level from a package pov.

Also, given where ":", "/", and the numbers (_0-9_) fall in ASCII, it also means:

```
"""Module comment."""

load("//foo:xyz.bzl", "xyz")
load("//foo2:mno.bzl", "mno")

def something():
    xyz.do()
    mno.do()
    return True
```

re-sorts to:

```
"""Module comment."""

load("//foo2:mno.bzl", "mno")
load("//foo:xyz.bzl", "xyz")

def something():
    xyz.do()
    mno.do()
    return True
```

So rather than a pure lexicographical sort of the string, should the string be split into the package and name, and that tuple be sorted for the order of the load statements?

**Comment by vladmos** [comment]
@ttsugriy

**Comment by ttsugriy** [comment]
that's an excellent suggestion! I don't have any objections and if there is a consensus around this proposal, I'd be happy to send a PR with implementation.

**Comment by thomasvl** [comment]
aside - I think '@' vs. ':' vs '/' all work out so loads from other repos also end up sorted right, but if you are changing things, you might want to do some tests cases and/or handing of it to make sure it is explicitly correct.

```
load("@SOMETHING//foo/bar:mno.bzl", "mno")
load("//local:xyz.bzl", "xyz")
load(":abc.bzl", "abc")
```

(The edge case may be files/directories that start with a number vs the external ones: _"2more:foo.bzl"_ vs _"@SOMETHING//bar:foo.bzl"_)

**Comment by ttsugriy** [comment]
@thomasvl, there is already a test for all forms of loads - https://github.com/bazelbuild/buildtools/blob/master/warn/warn_test.go#L492-L504 But I'll check if it does not handle some of your suggestions.
