### ISSUE TITLE
Include buildifier for OSX homebrew in the bazelbuild tap?

### ISSUE THREAD

**Issue by dpursehouse** [bazelbuild/buildtools#506]
bazel for OSX is included in homebrew via a custom tap: `bazelbuild/tap`.  However buildifer is still included in homebrew-core.

Would it be better to move buildifier also into the custom tap?

**Comment by vovkasm** [comment]
But bazel also included in homebrew core (https://github.com/Homebrew/homebrew-core/blob/master/Formula/bazel.rb), so please don't remove buildifier from there. If you need it in bazelbuild/tap, simple add it to that tap.

**Comment by dpursehouse** [comment]
I was under the impression (mistakenly, it seems) that bazel was no longer updated in homebrew-core.  If that's not the case, then it doesn't make sense to move buildifier.  Closing this issue.
