### ISSUE TITLE
Buildifier: allow to run on a directory (+ find files recursively)

### ISSUE THREAD

**Issue by gertvdijk** [bazelbuild/buildtools#516]
This is a feature request sparked in PR #495 by @brown.

Currently, `buildifier` only operates on single files. In order to check a whole project with plenty of Bazel-related files, it requires users to 'feed' it all relevant files. It would be awesome to have `buildifier` have the ability to ...:

* find files it understands automatically (`BUILD`, `BUILD.bazel`, `WORKSPACE`, `*.bzl`, etc.)
* recurse into subdirectories.

**Comment by alexeagle** [comment]
+1 this also causes it to be non-portable. On Angular we use a unix `find` command to pipe the files list to buildifier:
https://github.com/angular/angular/blob/cfe6581fc8c292dc7aa1aac07a461de64ebf1c36/package.json#L19
but our co-workers on Windows are stuck.

As @gertvdijk points out, we already know a priori which files are interesting to buildifier.

**Comment by laurentlb** [comment]
What should be the syntax?

* `buildifier some_dir`
* `buildifier some_dir/...`
* `buildifier -r some_dir`

**Comment by pmbethe09** [comment]
I like the 
`buildifier some_dir/...`
as it matches bazel wildcar syntax

**Comment by gertvdijk** [comment]
@laurentlb 

I like the `-r some_dir` option.

I strongly dislike the `some_dir/...` approach, because it would wrongly suggest that it's aware of Bazel's labels or that you could set `//...` to run it from the WORKSPACE root for example. That would be confusing, no?

I would not prefer the implicit mode without any option, but I would not object to it.

To elaborate a bit further on what was on my mind:
* (perhaps obvious) `-r` simply enables recursive behaviour on the paths, not related to the position on the command line, so that `buildifier -r -otheropt some_dir` will also work.
* (perhaps obvious) If I'm correct, buildifier accepts all remainder arguments as input files. With `-r`, it should accept those as multiple directories too.
* With `-r` given, a file/path may be omitted and it should behave as if `.` is given. This is similar to what most other tooling does, I believe, such as `grep -r` eliminates the need for a path argument.

HTH :smile:

**Comment by vladmos** [comment]
I've implemented it with -r flag (but not with omitted path) for now in #587.

**Comment by gertvdijk** [comment]
@vladmos 

Cool!

> (but not with omitted path) for now

That's totally fine for me, I'd consider it a nice to have.

**Comment by anandwana001** [comment]
> What should be the syntax?
> 
> * `buildifier some_dir`
> * `buildifier some_dir/...`
> * `buildifier -r some_dir`

Do we have an option to run `buildifier` on a current directory(Let's say foo/bar/) so that it finds all the required files and we don't want to provide the path when we are inside the (foo/bar/)?
`foo/bar % buildifier --lint=warn --mode=check --warnings=all`

**Comment by vladmos** [comment]
You can use something like `buildifier foo/bar/*.bzl` to format all .bzl files in the directory. Currently there's no analog for `-r` that would automatically find all Starlark files in a directory but not recursively.
