### ISSUE TITLE
`buildifier` rule fetches the whole of https://github.com/bazelbuild/bazel.git

### ISSUE THREAD

**Issue by Profpatsch** [bazelbuild/buildtools#526]
I sadly don’t have a CLI output because bazel makes it vanish after the fetch is complete (and you can’t copy auto-updating terminal).

Our rule looks like this:
```
# Run this to fix the errors in BUILD files.
buildifier(
    name = "buildifier-fix",
    mode = "fix",
    verbose = True,
)
```

and it starts fetches the bazel repo.

The whole repo takes >200s on our office connection and is basically impossible to wait on on a less potent one (>5 minutes on 1Mb/s). That’s bad.

My checkout of bazel is 750Mb, it’s a bit silly to download all that just to lint a bit of pseudo-python code.

**Comment by jwnimmer-tri** [comment]
Indeed, it would be helpful if every `git_repository` in the transitive workspace used either `tag=` or `shallow_since=`.  From a quick skim of the io_bazel_rules_go and bazel_gazelle deps.bzl files, I don't see a single use of either -- so _every_ git dependency seems to me like it will be fully cloned?

**Comment by laurentlb** [comment]
If the dependency on bazelbuild/bazel is just for some proto files, we may want to copy them in this repo instead?

**Comment by ash2k** [comment]
@laurentlb it's been reported a while ago https://github.com/bazelbuild/buildtools/issues/143
