### ISSUE TITLE
build: WalkOnce doesn't visit LoadStmt children

### ISSUE THREAD

**Issue by jayconrod** [bazelbuild/buildtools#527]
`build.WalkOnce` is supposed to call its callback argument for each child of its `Expr` argument. It doesn't seem to have a case for `LoadStmt`. This prevents tools from modifying module names and symbols in load statements using `build.Edit`, which calls `WalkOnce` internally. One of the tools in the Gazelle repo needed a special case to work around this.

**Comment by vladmos** [comment]
`LoadStmt` nodes can have children only one level deep, so it's enough to fix the `edit.UsedSymbols` function to check if the last element of the stack is a load statement. Please check if #533 works for you, I'll submit it if so.
