### ISSUE TITLE
Add a command line option to show the version

### ISSUE THREAD

**Issue by dpursehouse** [bazelbuild/buildtools#54]
When committing a change that reformats files, it is useful to mention which version of buildifier was used.

The version is also useful when reporting issues here.

**Comment by rishiloyola** [comment]
I would like to work on this bug. Can you please guide me about how can I get the current version of buildifier?

**Comment by pmbethe09** [comment]
Probably we want to use rules_go new link-stamping, and then add a
'-version' flag that prints it.

https://github.com/bazelbuild/rules_go/commit/0fe511a21b1118c937b515edb21e7ec4cc587391

**Comment by rishiloyola** [comment]
So the user will pass the version through the linkstamp attribute of go_binary rule, and then by generating new link-stamping, we will inject the new variable into the binary file. 
Please correct me if I am wrong.

**Comment by pmbethe09** [comment]
@jayconrod can you comment on how buildifier could use the linkstamp attribute?

**Comment by jayconrod** [comment]
@rishiloyola It's a little more complicated. See [stamped_bin](https://github.com/bazelbuild/rules_go/tree/master/examples/stamped_bin) within rules_go for an example.

* Create a script that prints the version information. Let's call it status.sh. See [get_workspace_status](https://github.com/bazelbuild/bazel/blob/master/tools/buildstamp/get_workspace_status) within Bazel for an example. Here's a short version:

```bash
#!/bin/bash

echo BUILDIFIER_VERSION 0.4.3
echo BUILD_SCM_REVISION "$(git rev-parse HEAD)"
```

* Add global variables with the same names as above to some package. It's probably simplest to add to the main package.

```go
package main

var BUILDIFIER_VERSION = "redacted"
var BUILD_SCM_REVISION = "redacted"
```

* Add the linkstamp attribute to the `go_binary` rule. This should be set to the package that contains the global variables added above.

```skylark
go_binary(
    name = "buildifier",
    srcs = ["buildifier.go"],
    visibility = ["//visibility:public"],
    linkstamp = "main",
    deps = [
        "//build:go_default_library",
        "//differ:go_default_library",
        "//tables:go_default_library",
    ],
```

* When building a binary for release, add the command line flag `--workspace_status_command=./status.sh`. Without this flag, the status script will not be executed, and the stamp variables will not be set.

Hope this helps.

**Comment by rishiloyola** [comment]
I think so the version of rules_go which is used by buildifier does not support linkstamp method of go_binary rule.
We need to update it.

**Comment by rishiloyola** [comment]
Also, Are we planning to make it more generic? 
I wrote the status.sh file. And test it locally. It's working fine for me.
Where can I push my code?

**Comment by aljabrr** [comment]
Has this issue been fixed? If so should this issue not be close?

**Comment by dpursehouse** [comment]
I just upgraded to version 0.4.5 with homebrew on OSX, and it looks like this:

```
$ buildifier --version
buildifier version: redacted
buildifier scm revision: redacted
```

**Comment by dpursehouse** [comment]
Problem seems to be that homebrew is not passing the workspace option when building it.

https://github.com/Homebrew/homebrew-core/pull/12413

**Comment by davido** [comment]
Same here. The -version CLI option is even not shown when buildifier executed with -help:

```
  $ bazel-bin/buildifier/buildifier  -help
usage: buildifier [-d] [-v] [-mode=mode] [-path=path] [files...]
  $ bazel-bin/buildifier/buildifier  -version
buildifier version: redacted 
buildifier scm revision: redacted
```

I'm on: 631e912db128c330ca53637d78692b42e3bed39a

**Comment by davido** [comment]
This patch fixed the problem:

```
diff --git a/buildifier/buildifier.go b/buildifier/buildifier.go
index a9aaeff..4582030 100644
--- a/buildifier/buildifier.go
+++ b/buildifier/buildifier.go
@@ -32,8 +32,8 @@ import (
        "github.com/bazelbuild/buildtools/tables"
 )
 
-var buildifierVersion = "redacted"
-var buildScmRevision = "redacted"
+var buildifierVersion = "42"
+var buildScmRevision = "42"
 
 var (
        // Undocumented; for debugging.
```

Now the version is shown correctly:

```
   $ bazel-bin/buildifier/buildifier -version
buildifier version: 42 
buildifier scm revision: 42
```

**Comment by davido** [comment]
OK, I think I figured it out. `status.sh should be executed manually, and the result manually imported in `buildifier/buildifier.go`?

```
$ ./status.sh 
buildifierVersion 0.4.5
buildScmRevision 631e912db128c330ca53637d78692b42e3bed39a
```

Now, the the result should be imported into `buildifier/buildifier.go`:

```
diff --git a/buildifier/buildifier.go b/buildifier/buildifier.go
index a9aaeff..d174cf5 100644
--- a/buildifier/buildifier.go
+++ b/buildifier/buildifier.go
@@ -32,8 +32,8 @@ import (
        "github.com/bazelbuild/buildtools/tables"
 )
 
-var buildifierVersion = "redacted"
-var buildScmRevision = "redacted"
+var buildifierVersion = "0.4.5"
+var buildScmRevision = "631e912db128c330ca53637d78692b42e3bed39a"
 
 var (
        // Undocumented; for debugging.
```

Now building it, it seems to work as expected:

```
$ bazel-bin/buildifier/buildifier -version
buildifier version: 0.4.5 
buildifier scm revision: 631e912db128c330ca53637d78692b42e3bed39a
```

**Comment by dpursehouse** [comment]
@davido doesn't it work to pass the `--workspace-status` option?

```
bazel build --workspace_status_command=./status.sh //buildifier
```

**Comment by davido** [comment]
Of course not:

```
davido@wizball:~/projects/buildtools (master=)$ bazel build --workspace_status_command=./status.sh //buildifier
INFO: Found 1 target...
Target //buildifier:buildifier up-to-date:
  bazel-bin/buildifier/buildifier.a
  bazel-bin/buildifier/buildifier
INFO: Elapsed time: 0.360s, Critical Path: 0.05s

davido@wizball:~/projects/buildtools (master=)$ bazel-bin/buildifier/buildifier -version
buildifier version: redacted 
buildifier scm revision: redacted 
```

I don't see the code responsible for considering the output from `./status.sh`. the version vars are hard coded in `buildifier/buildifier.go`.

**Comment by dpursehouse** [comment]
It works for me on OSX.

```
buildifier $ git fetch
buildifier $ git reset --hard origin/master
HEAD is now at 631e912 Merge pull request #106 from vladmos/fix_buildozer
buildifier $ bazel build --workspace_status_command=./status.sh //buildifier
.............
INFO: Found 1 target...
Target //buildifier:buildifier up-to-date:
  bazel-bin/buildifier/buildifier.a
  bazel-bin/buildifier/buildifier
INFO: Elapsed time: 28.569s, Critical Path: 6.20s
buildifier $ ./bazel-bin/buildifier/buildifier -version
buildifier version: 0.4.5
buildifier scm revision: 631e912db128c330ca53637d78692b42e3bed39a
```

**Comment by davido** [comment]
@dpursehouse Thanks. Looks that sometimes that works but sometimes not. And I found the code. There is `linkstamp` attribute in https://github.com/bazelbuild/rules_go#go_binary, that is set to `main` package in buildifier build. Now, the `status.sh` exports the vars into `bazel-out/volatile-status.txt` and `go_binary` adds them to the linker under this package name `main`:

```
$ cat bazel-out/volatile-status.txt 
BUILD_TIMESTAMP 1497893119481
buildScmRevision 631e912db128c330ca53637d78692b42e3bed39a
buildifierVersion 0.4.5
```

**Comment by jayconrod** [comment]
If I remember correctly, Bazel writes the output of `status.sh` into either `volatile-status.txt` or `stable-status.txt` depending on whether the key starts with `BUILD_`. The former is considered dirty whenever it changes, but the latter is not.

Maybe try renaming the flags to `BUILD_SCM_REVISION` and `BUILD_VERSION` and see if that removes the flakiness?

**Comment by davido** [comment]
Actually as documented in go_binary, both files are considered:

```
cat bazel-out/local-fastbuild/bin/buildifier/bazel-out/local-fastbuild/bin/buildifier/buildifier.a.GoLinkFile.params
[...]
STAMP_XDEFS=()
while read -r key value || [[ -n $key ]]; do
  STAMP_XDEFS+=(-X "main.$key=$value")
done < bazel-out/stable-status.txt
while read -r key value || [[ -n $key ]]; do
  STAMP_XDEFS+=(-X "main.$key=$value")
done < bazel-out/volatile-status.txt
```

So actually this should work as is.

**Comment by davido** [comment]
We install buildifier like this in [our CI docker image](https://gerrit-review.googlesource.com/#/c/gerrit-ci-scripts/+/139511/30/jenkins-docker/slave-bazel/Dockerfile@16):

```
 $ GOPATH=/usr go get github.com/bazelbuild/buildtools/buildifier && \
 $ chmod a+rx /usr/bin/buildifier
```

Asked for the version, we get:

```
jenkins@5a87a2b058e5:~$ buildifier -version
buildifier version: redacted 
buildifier scm revision: redacted 
```

If I build it from source, with `--workspace_status_command=./status.sh` option, it show the version:

```
jenkins@5a87a2b058e5:~/gerrit$ ~/bin/buildifier  --version
buildifier version: 0.6.0 
buildifier scm revision: 80f533010c61a699197f7dd28a27e0012d339f89
```

**Comment by davido** [comment]
On most recent Bazel version (0.14.0) it work now:

```
  $ bazel build --workspace_status_command=`pwd`/status.sh //buildifier
  $ bazel-bin/buildifier/linux_amd64_stripped/buildifier --version
  buildifier version: 0.11.1 
  buildifier scm revision: 405641a50b8583dc9fe254b7a22ebc2002722d17 
```
