### ISSUE TITLE
Buildifier crashes formatting file

### ISSUE THREAD

**Issue by keith** [bazelbuild/buildtools#541]
Using buildifier from this sha 56771622edeeb5070228eb91704ea35d47606e97 I get a crash when formatting this file:

```python
load("@bazel_skylib//lib:paths.bzl", "paths")

def _bitcode_linkopts(ctx):
    bitcode_mode = str(ctx.fragments.apple.bitcode_mode)
    # We don't have to check for device or simulator because bazel does this
    # for us https://github.com/bazelbuild/bazel/blob/2a116372382aedbf8a39477e0ea1123903ab5479/src/main/java/com/google/devtools/build/lib/rules/apple/AppleConfiguration.java#L358-L365
    if bitcode_mode != "embedded":
        return struct(objc = apple_common.new_objc_provider())

    root_build_dir = paths.dirname(ctx.build_file_path)
    symbolmap_path = paths.join(
        ctx.bin_dir.path,
        root_build_dir,
        # This is where bazel requires this file to end up
        ctx.attr.target_name + ".apple_binary.bcsymbolmap",
    )
    linkopts = [
        "-fembed-bitcode",
        "-Wl,-bitcode_verify",
        "-Wl,-bitcode_hide_symbols",
        "-Wl,-bitcode_symbol_map",
        "BITCODE_TOUCH_SYMBOL_MAP=" + symbolmap_path,
    ]

    return struct(
        objc = apple_common.new_objc_provider(
            linkopt = depset(linkopts, order = "preorder"),
        ),
    )

bitcode_linkopts = rule(
    attrs = {
        "target_name": attr.string(mandatory = True),
    },
    fragments = ["apple"],
    implementation = _bitcode_linkopts,
)
```

The issue is that it wants a newline under the `bitcode_mode` line. The error is just:

```
./bazel/bitcode_linkopts.bzl:
buildifier: ./bazel/bitcode_linkopts.bzl: internal error: runtime error: invalid memory address or nil pointer dereference
```

I'm running buildifier through bazel with this rule:

```
buildifier(
    name = "buildifier.warn",
    lint_mode = "warn",
)
```

**Comment by vladmos** [comment]
I can't reproduce the issue: `git checkout 5677162 && bazel build //buildifier && bazel-bin/buildifier/darwin_amd64_stripped/buildifier --type=bzl --lint=warn < repro.bzl` (where `repro.bzl` is a file containing your example) formats the file and shows warnings as expected without runtime errors.

**Comment by vladmos** [comment]
Also tried to run it as a Bazel rule: https://gist.github.com/vladmos/a72a3ed867293e3ad69e2621a997a803

`bazel run //:buildifier.warn` reports no crashes.

**Comment by keith** [comment]
There must be a problem with more of the files that causes it. This was the second time I've seen this. I'll try to provide more info next time

**Comment by vladmos** [comment]
Have you encountered any more crashes?

I've run buildifier on all .bzl files we have, the formatter doens't crash on them, the linter does on one file which is not valid for Bazel because it loads a symbol from a string which is not a label. But in this case the error message was `index out of range`, not `invalid memory address`.

**Comment by keith** [comment]
I haven't. We can close this for now and I can resubmit with more info if we experience them again in the future
