### ISSUE TITLE
Make "BUILD" being the name of BUILD files configurable

### ISSUE THREAD

**Issue by swolchok** [bazelbuild/buildtools#55]
Buck thinks that its input files should be called `BUCK`. Since buildozer also doesn't seem to have a way to accept a BUILD file on stdin (and seems to want to know the target to modify, not just the BUILD file path), this makes using buildozer with appropriately-formatted `BUCK` files difficult.

**Comment by pmbethe09** [comment]
not sure I follow.  You can call:
`buildifier some/path/BUCK other/path/BUCK `
and it will run on those files.

**Comment by swolchok** [comment]
> `buildifier some/path/BUCK other/path/BUCK`

Does the same hold for buildozer, not buildifier? It didn't seem to, but it's possible I was doing it wrong. `buildozer path/to/BUCK "add some_attribute True` gave me an error like `path/to/BUCK/BUILD: stat path/to/BUCK/BUILD: not a directory`, as did `buildozer path/to/BUCK :some_target_in_the_buck_file "add some_attribute True"`.

**Comment by pmbethe09** [comment]
... oops ... you wrote 'buildozer' and I read 'buildifier'.

You are absolutely right, 'BUILD' is hardcoded in several places here:
https://github.com/bazelbuild/buildifier/blob/master/edit/buildozer.go

and will need to get changed to allow for 'BUILD.bazel' and 'BUCK'

**Comment by swolchok** [comment]
FWIW, I think it's also hardcoded in https://github.com/bazelbuild/buildifier/blob/master/edit/edit.go, so I'm not sure how buildifier works with `BUILD.bazel` and `BUCK` either. :\

**Comment by swolchok** [comment]
Is this an issue the buildifier team is interested in fixing, or should I put a PR together? If the latter, does a command-line flag seem like the way to go?

**Comment by pmbethe09** [comment]
Instead of a flag, why not just look for suffixes in order: {BUILD.bazel,
BUILD, BUCK}

**Comment by swolchok** [comment]
Should we close this?
