### ISSUE TITLE
buildifier --lint function-docstring seems somewhat random on when arguments must be documented

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/buildtools#576]
It isn't clear when a function must have its argument documented and when it doesn't have too. Given a file with this:

```python
"""module

about module.
"""

load(
    "some/path:helper.bzl",
    "helper",
    _foo_rule = "foo_rule",
)

def foo_rule1(name, deps = [], **kwargs):
    """Macro docstring."""
    _foo_rule(name, deps = deps, **kwargs)

def foo_rule2(name, deps = [], **kwargs):
    """Macro docstring."""
    helper(name + "_something")
    _foo_rule(name, deps = all_deps, **kwargs)

def foo_rule3(name, deps = [], **kwargs):
    """Macro docstring."""
    helper(name + "_something")
    _foo_rule(name, deps = deps, **kwargs)
    helper(name + "_something2")

def foo_rule4(name, deps = [], **kwargs):
    """Macro docstring."""
    helper(name + "_something")
    all_deps = deps + [":" + name + "_something"]
    _foo_rule(name, deps = all_deps, **kwargs)

def foo_rule5(name, deps = [], **kwargs):
    """Macro docstring."""
    all_deps = deps + [":" + name + "_something2"]
    _foo_rule(name, deps = deps, **kwargs)
    helper(name + "_something2")

def foo_rule6(name, deps = [], **kwargs):
    """Macro docstring."""
    helper(name + "_something")
    all_deps = deps + [":" + name + "_something"]
    helper(name + "_something2")

def foo_rule7(name, deps = [], **kwargs):
    """Macro docstring."""
    helper(name + "_something")
    all_deps = deps + [":" + name + "_something"]
    _foo_rule(name, deps = all_deps, **kwargs)
    helper(name + "_something2")
```

`buildifier --lint=warn foo.bzl` produces:

```
foo.bzl:46: function-docstring: Arguments "name", "deps", "**kwargs" are not documented. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#function-docstring)
```

Only the last one gets flagged.  It appears to take a combination of work and then suddenly the lint checks decide the args need to be documented.   I'd sorta expect if there is no _Args_ block, I should never have to document them (developer's choice), but it doesn't seems instead to be based on some thing else?

**Comment by laurentlb** [comment]
The condition is: the function has at least 5 statements and it is not private.

**Comment by thomasvl** [comment]
What counts as a "statement"?  There's only 4 lines of "code" in the one that warn, does the comment itself count as the 5th?  How would a conditional count (one statues, or does the then/else clause count toward the total statements)?

**Comment by laurentlb** [comment]
Statement is based on the grammar: https://github.com/bazelbuild/starlark/blob/master/spec.md#grammar-reference

I think this counts as 3 statements (1 conditional + 2 inner statements):
```python
if cond:
    x
else:
    y
```

**Comment by vladmos** [comment]
A docstring counts as a statement, block statement (if-else or for) counts as one statement + number of the inner statements.

Short and private functions (with names starting with `_`) are allowed to have no or incomplete docstrings, however if you document some of the arguments but not all of them in such functions, buildifier will still show a warning.

**Comment by thomasvl** [comment]
Any chance this logic can get a `warning` arg control or `function-docstring` can get broken up so this can be controlled?  Right now `function-docstring` seems to be the single warning type for completely missing comments, a single arg being missing, a single arg still documented after it was removed from the signature.

In our case, we have a few _rules_ that for _reasons_ actually have to be made up of a macro and private rule(s).  The macro does some preprocessing/validation before handing things off to the rule; currently this 5 statement threshold is what occasionally crops up saying we need doc strings in some cases but not other; but the reality is the rule always has more complete docs and forcing the duplication tends to mean they drift/aren't complete.

**Comment by vladmos** [comment]
Would it be enough if it's split into `function-docstring` (that just checks for the existence for public functions with more or equal than 5 statements), `function-docstring-header`, `function-docstring-args`, `funciton-docstring-return` (all are applied only if a docstring exists)?

**Comment by thomasvl** [comment]
> Would it be enough if it's split into `function-docstring` (that just checks for the existence for public functions with more or equal than 5 statements), `function-docstring-header`, `function-docstring-args`, `funciton-docstring-return` (all are applied only if a docstring exists)?

That sounds like it could work since it provides more granular controls.
