### ISSUE TITLE
buildifier --lint issues bogus duplicated-name when using a path to a file and it has a loop

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/buildtools#577]
Given a `BUILD` file with:

```
licenses(["notice"])

[
    cc_library(
        name = x,
        srcs = [x + ".cc"],
    )
    for x in ["foo"]
]
```

`buildifier --lint=warn BUILD` pass just fine; however `buildifier --lint=warn src/BUILD` results in:

```
src/BUILD:5: duplicated-name: A rule with name `src' was already found on line 1. Even if it's valid for Blaze, this may confuse other tools. Please rename it and use different names. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#duplicated-name)
```

If you remove the `licenses(["notice"])`, the issue goes away.  If you remove the loop and just have one rule the issue goes away.

**Comment by laurentlb** [comment]
I think it has been fixed recently (I haven't double-checked).

**Comment by vladmos** [comment]
I confirm this is no longer reproducible at HEAD.

**Comment by thomasvl** [comment]
Is there a release planned?  This is one of the issue preventing us from being able to use buildifier on some of our sources?
