### ISSUE TITLE
Some way to query the default lint warnings

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/buildtools#579]
Now that all warnings aren't enable by default, it would be nice if there was some way to see what is in the default set, i.e. - which ones are optional.  I'd say the WARNING.md could be used, but since that seems to be manually updated, I worry it wouldn't always match what so getting the list directly from buildifier seems more authoritative.

**Comment by vladmos** [comment]
I'll update the WARNINGS.md file for now. There shouldn't be many warnings/fixes that are not enabled by default.
