### ISSUE TITLE
`uninitialized` warning don't take `fail` into account as not returning

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/buildtools#594]
Given (reduced from rules_swift):

```python
# testing.bzl
"""module comment"""

load("@bazel_skylib//lib:types.bzl", "types")

def _run_shell_action(
        bazel_xcode_wrapper,
        actions,
        **kwargs):
    """Macro comment

    Args:
        bazel_xcode_wrapper: A `File` representing the Bazel Xcode wrapper executable for the
            action.
        actions: The `Actions` object with which to register actions.
        **kwargs: Additional arguments that are passed to `actions.run_shell`.
    """
    remaining_args = dict(**kwargs)

    user_tools = remaining_args.pop("tools", [])
    if types.is_list(user_tools):
        tools = [bazel_xcode_wrapper] + user_tools
    elif type(user_tools) == type(depset()):
        tools = depset(direct = [bazel_xcode_wrapper], transitive = [user_tools])
    elif user_tools:
        fail("'tools' argument must be a sequence or depset.")

    # Prepend the wrapper executable to the command being executed.
    user_command = remaining_args.pop("command", "")
    if types.is_list(user_command):
        command = [bazel_xcode_wrapper.path, "/usr/bin/xcrun"] + user_command
    else:
        command = "{wrapper_path} /usr/bin/xcrun {user_command}".format(
            user_command = user_command,
            wrapper_path = bazel_xcode_wrapper.path,
        )

    actions.run_shell(
        command = command,
        tools = tools,
        **remaining_args
    )
```

Results in:

```
$ buildifier --lint=warn testing.bzl 
testing.bzl:40: uninitialized: Variable "tools" may not have been initialized. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#uninitialized)
testing.bzl:40: uninitialized: Variable "tools" may not have been initialized. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#uninitialized)
```

**Comment by vladmos** [comment]
The issue that you see the warning twice has already been fixed. It used to match the argument name by mistake (`tools =`).

The warning message itself is correct, the variable `tools` is not initialized in case none of the `if` conditions are true. If you replace `elif user_tools:` with `else:` the warning will disappear, buildifier already takes `fail()` statements into account.

**Comment by thomasvl** [comment]
> The warning message itself is correct, the variable `tools` is not initialized in case none of the `if` conditions are true. If you replace `elif user_tools:` with `else:` the warning will disappear, buildifier already takes `fail()` statements into account.

Ah, I was thinking if it was a if it was a `string` it wiould hit that last `elif`, but it if is an empty string, then that will also fail.  Thanks.

**Comment by vladmos** [comment]
Note that even if it's guaranteed that at least one of the if/elif conditions are true, buildifier still won't analyze that and assume that all branches are potentially reachable. The workaround is to add something like

    ...
    else:
        fail("unreachable")
