### ISSUE TITLE
ExpandDirectories not working as intended?

### ISSUE THREAD

**Issue by pcj** [bazelbuild/buildtools#614]
From what I can tell the `utils.ExpandDirectories` is supposed to return a list of regular starlark files.  As currently written, it also includes inputs like:

`{WORKSPACE_ROOT}/foo/bar/build` (a directory named build)
`{WORKSPACE_ROOT}/foo/bar/workspace` (a directory named workspace)
`{WORKSPACE_ROOT}/proto/build/build.proto` (a proto file)

**Comment by vladmos** [comment]
Regarding the proto file, buildifier currently detects `build.*` and `*.build` as BUILD files. Maybe with `-r` it should be stricter and only accept `BUILD` and `BUILD.bazel` files.
