### ISSUE TITLE
load-on-top warning for BUILD files

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/buildtools#651]
When a load statement is not at the top of the file, I get this warning:

```
/tmp/z.bzl:6: load-on-top: Load statements should be at the top of the file. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#load-on-top)
```

However, it's not enabled in BUILD files. I think we should do it (but not in WORKSPACE files).

**Comment by vladmos** [comment]
It was intially enabled but was conflicting with some BUILD files generators. I'll eventually re-enable it again.

**Comment by beasleyr-vmw** [comment]
Was this resolved by https://github.com/bazelbuild/buildtools/pull/725 ?

**Comment by vladmos** [comment]
Yes.
