### ISSUE TITLE
Add ability to disable print warnings

### ISSUE THREAD

**Issue by BenDiuguid** [bazelbuild/buildtools#661]
With the implementation of #653 there isn't a documented way of disabling the `print()` warning.

i.e., `# buildozer: disable=print` does not work.

**Comment by thomasvl** [comment]
Even worse, since starlark still had no way to for rules/macros to issue warnings, the only option is to use `print`, having this in the default set seems wrong given the language doesn't provide the tools to do what is needed and this is the only way to do it.

**Comment by laurentlb** [comment]
If we cannot disable the warning, it's a bug.
