### ISSUE TITLE
Warn against potentially overly nested depsets

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/buildtools#679]
In Bazel, depsets are not always used efficiently. API changes (https://github.com/bazelbuild/bazel/issues/5817) encourage users to write the efficient solution. 

We can statically detect bad patterns. For example, this is sometimes used to add things to a depset:

```python
x = depset(..., transitive = [..., x, ...])
```

If this pattern is used inside a `for` loop, we should report a warning because it can lead to overly nested depsets (which lead to performance problems).

**Comment by brandjon** [comment]
Nice! @c-parsons and I were talking about this idea just the other day, had no idea you were already implementing it!
