### ISSUE TITLE
Buildifier removes some comments

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/buildtools#68]
[   # This line will be eaten by buildifier
    # but not this line.
    cc_binary(
        name = "something_%s_useful" % lang,
    )
    for lang in li]

**Comment by forumulator** [comment]
I'm working on this right now. Actually slight correction, there needs to be an input like
```python
[a for b in c]

[ #comment on the first line of a container with the opening [ or ( or { will be eaten
]
```
for the bug to materialize

**Comment by vladmos** [comment]
Currently buildifier doesn't allow to make comment on a multiline list, for example:

    items = [
        a,
        b,
    ]  # a list of items

also it doesn't allow commenting on a function call:

   foo(x)  # bar

I'm working on this issue and I'd like to remove these restrictions as they seem to be related to the initial problem. Are there any objections / reasons why buildifier is implemented this way?

**Comment by vladmos** [comment]
Another example of a missing comment:

    [
      x
      for x in y #foo
      if x # bar
    ]

is formatted to

    [
      x
      for x in y
      if x
    ]

due to a bug in the printer.
