### ISSUE TITLE
Buildifier Readme.md

### ISSUE THREAD

**Issue by blackliner** [bazelbuild/buildtools#689]
Hi, if i "Checkout the repo and then <snip> bazel build //buildifier" as stated in the readme, how do i actually run buildifier? The built ran without errors, but i can't find an executable.

Do i manually need to install it to some path, or add some dir to PATH? If there is a way, please add it to the readme.

I used Ubuntu 18.04LTS.

**Comment by vladmos** [comment]
Bazel creates the binaries in the `bazel-bin/` subdirectory, `bazel build //buildifier` should show the actual path of the binary, for example:

    INFO: Analyzed target //buildifier:buildifier (0 packages loaded, 0 targets configured).
    INFO: Found 1 target...
    Target //buildifier:buildifier up-to-date:
      bazel-bin/buildifier/linux_amd64_stripped/buildifier
    INFO: Elapsed time: 0.196s, Critical Path: 0.01s
    INFO: 0 processes.
    INFO: Build completed successfully, 1 total action

**Comment by blackliner** [comment]
thanks, that row doesn't show up if you: bazel build ...
