### ISSUE TITLE
Buildifier should support asterisk argument

### ISSUE THREAD

**Issue by eytankidron** [bazelbuild/buildtools#699]
I've come across an option in python, where you can specify an asterisk (*) as an argument to a function. This has the effect of forcing all following arguments to be specified by keyword rather than positionally. Here is where I saw it: https://medium.com/@boxed/keyword-argument-confusion-in-python-59105c5a1159.

It also apparently works in starlark. But buildifier 0.22.0 fails to parse this * notation.

**Comment by vladmos** [comment]
That's already implemented: #677 
Buildifier 0.22.0 is pretty old, the last version is 0.28.0, where the asterisk syntax is still not supported (it was implemented a week later after the release). 0.29.0 will be released as soon as Bazel 0.29 is released (https://github.com/bazelbuild/bazel/issues/8572)
