### ISSUE TITLE
certain buildifier runs are not idempotent

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/buildtools#70]
after running buildifier, you would expect the 2nd time around to be unchanged/identical, but apparently not for some cases:

example
$ cat > /tmp/dir/BUILD
py_test(
    tags = ["manual", "local"],  # comment                                                   
)

$ cat /tmp/dir/BUILD | buildifier
py_test(
    tags = [
        "manual",
        "local",
    ],  # comment
)

$ cat /tmp/dir/BUILD | buildifier | buildifier
py_test(
    tags = [
        "manual",
        "local",  # comment
    ],
)

**Comment by vladmos** [comment]
The issue has been fixed in #102
