### ISSUE TITLE
Warn for private bzl files

### ISSUE THREAD

**Issue by laurentlb** [bazelbuild/buildtools#702]
As part of the discussions aroundd visibility for bzl files (https://groups.google.com/d/msg/bazel-dev/t4dloyISzLU/N-Qox97LCgAJ), it was suggested to have a warning when loading a file in a "internal" directory.

We can look for directories named "internal" or "private".
For example, we can make sure that `foo/bar/internal/sub/file.bzl` can be loaded only from `foo/bar/*.bzl`.

The convention is already used in real world code, e.g the "private" directory in https://github.com/bazelbuild/rules_go/tree/master/go.

cc @alandonovan

**Comment by alandonovan** [comment]
> we can make sure that foo/bar/internal/sub/file.bzl can be loaded only from foo/bar/*.bzl.

or from foo/bar/.../*.bzl.

**Comment by vladmos** [comment]
What about `BUILD` files inside `foo/bar`?

**Comment by laurentlb** [comment]
Yes, BUILD files too.

So we have:
`@rules_go//private/foo:bar.bzl` is visible from `@rules_go//...`
`@rules_go//go/private/foo:bar.bzl` is visible from `@rules_go//go/...`
