### ISSUE TITLE
Buildozer is not quoting strings when setting python_version

### ISSUE THREAD

**Issue by chrismcbride** [bazelbuild/buildtools#703]
I have a large python project where Id like to set `srcs_version="PY2"` and `python_version="PY2"` for all py_test and py_binary targets. Im using the latest buildifer from HEAD (39965566496b9b86414d553fbd776f9b47c74bcd).

Given a BUILD file like so:

```python
py_binary(
    name = "bin",
    srcs = [
        "main.py",
    ],
)
```

I run `buildozer 'set_if_absent srcs_version PY2' //:bin` and get:

```python
py_binary(
    name = "bin",
    srcs = [
        "main.py",
    ],
    srcs_version = "PY2",
)
```
Great! Now if I do the same thing for python_version `buildozer 'set_if_absent python_version PY2' //:bin`, I get:

```python
py_binary(
    name = "bin",
    srcs = [
        "main.py",
    ],
    python_version = PY2,
    srcs_version = "PY2",
)
```

PY2 is not added as a string.

**Comment by pmbethe09** [comment]
What if you wrap the "PY2" inside the ''?  Does that work or does something
strip the double-quote?

**Comment by chrismcbride** [comment]
ah yea quoting the string works, thanks

**Comment by pmbethe09** [comment]
Makes sense, buildozer knows the grammar, but not the semantic meaning
of python_version -- it is unaware that the expected RHS is a string.

**Comment by vladmos** [comment]
FYI, even if Buildozer knows that the argument is a string you can still quote it, and it shouldn't be double-quoted, so you can always use `"PY2"` if you know that it should be a string literal.
