### ISSUE TITLE
buildifier: additional file patterns when invoked via bazel

### ISSUE THREAD

**Issue by tsawada** [bazelbuild/buildtools#704]
Our repository has a bunch of BUILD files named `BUILD.*.bazel` to feed into `http_archive.build_file`.
It'd be nice if `bazel run //:buildifier` can also lint those files in addition to what it currently considers as BUILD/WORKSPACE file.

Let us know if we should name our external BUILD files differently.

**Comment by vladmos** [comment]
If you rename the files to `BUILD.bazel` or `BUILD.oss` (same with `WORKSPACE`), buildifier will correctly detect the file type and also format/lint/fix them with the `-r` flag.

Is it possible to do it in your case?

**Comment by tsawada** [comment]
Naming external BUILD file as `BUILD.bazel` will probably cause errors on `bazel build` (as it references files that are not there). It is possible to use `BUILD.oss` name however we can have only one BUILD file per a directory, and I have never seen anybody using this name.

I think using filename `BUILD.*.bazel` for external BUILD files are quite common (such as [this](https://github.com/bazelbuild/rules_go/blob/master/go/private/BUILD.sdk.bazel) in rules_go) and it'd be very nice if buildifier can reformat all these BUILD files that are already out there.
