### ISSUE TITLE
'bzl-visibility' checks fail for multiple references to the same workspace

### ISSUE THREAD

**Issue by ashgti** [bazelbuild/buildtools#718]
The 'bzl-visibility' check is causing warnings if a rule uses a load statement that changes between '@//', '//' and '@workspace_name//', even if all three are pointing to the same workspace on disk. 

For example, the [bazelrules/rules_apple](https://github.com/bazelbuild/rules_apple) will fail with the following error:

```
$ buildifier.mac -lint warn ./apple/apple.bzl
./apple/apple.bzl:18: bzl-visibility: Module "@build_bazel_rules_apple//apple/internal:apple_framework_import.bzl" can only be loaded from files located inside "@build_bazel_rules_apple//apple", not from "//apple". (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#bzl-visibility)
```

**Comment by vladmos** [comment]
It's currently not possible for buildifier to expand workspace names correctly, the solution is to make the check non-default so that it will only be used when explicitly mentioned (or with `--warnings=all`).
