### ISSUE TITLE
undefined: strings.Builder

### ISSUE THREAD

**Issue by tshasc** [bazelbuild/buildtools#722]
I am trying to execute below command with which copy buildifier to my local, but looks like it was broken

C02SY015H03M:go ***$ /usr/local/go/bin/go get -u github.com/bazelbuild/buildtools/buildifier
# github.com/bazelbuild/buildtools/warn
src/github.com/bazelbuild/buildtools/warn/warn_operation.go:174:16: undefined: strings.Builder

@vladmos

**Comment by vladmos** [comment]
You're probably using an old version of go, `strings.Builder` was indroduced in go 1.10.

**Comment by tshasc** [comment]
thanks, it works after I upgrade to go 1.13
