### ISSUE TITLE
[Help-Wanted] Is there any way to disable one line in BUILD to escape the buildifier check?

### ISSUE THREAD

**Issue by csuyangpeng** [bazelbuild/buildtools#745]
hi,
     Is there any way to disable one line in BUILD to escape the buildifier check?
  Because of some reason, i want to keep the deps order for one BUILD file.
  I know the lint has `// NOLINT` to disable the lint check for the line with the tag.

**Comment by vladmos** [comment]
You can disable a certain type of warnings with a special comment: `# buildifier: disable=<category_name>`.

**Comment by kigster** [comment]
Is this documented anywhere?

**Comment by vladmos** [comment]
Yes: https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#how-to-disable-warnings

**Comment by zixing0131** [comment]
> You can disable a certain type of warnings with a special comment: `# buildifier: disable=<category_name>`.

Hi @vladmos, I encountered the same issue on this. (i.e. I want to preserve the parameter order in one target of the BUILD.bazel file). I looked through the list and cannot find the one with right category, as I don't think `unsorted-dict-items` will do. Which category I should use? Thanks!
