### ISSUE TITLE
unsorted-dict-items suggests strange ordering for 'exports'

### ISSUE THREAD

**Issue by c-parsons** [bazelbuild/buildtools#760]
Am I missing something with regards to the suggested ordering warned by `unsorted-dict-items`?

In a list of attributes, buildifier suggests the following ordering:

```
        "dynamic_deps"
        "linkopts"
        "preloaded_deps"
        "visibility_file"
        "exports"
        "_cc_toolchain"
```

`exports` seems out of place, here. If we rename it to `exportsfoo`, buildifier suggests a sensible ordering (`exportsfoo` should go before `linkopts`)

IIUC, the [documentation](https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#dictionary-items-should-be-ordered-by-their-keys) for this warning only remarks potentially overriding the ordering.

**Comment by vladmos** [comment]
It seems that the check uses the same list of exceptions as the function that sorts the rule attributes (e.g. "name" should always be the first, etc.): https://github.com/bazelbuild/buildtools/blob/master/tables/tables.go#L176

However perhaps the only item in the list that makes sense for dicts is "//conditions:default" which should be the last in select statements and is unlikely to appear anywhere else.
