### ISSUE TITLE
Repo needs a new name

### ISSUE THREAD

**Issue by pmbethe09** [bazelbuild/buildtools#78]
With the addition of buildozer, and soon unused_deps, the repo name should be made more generic.

Our current favorite is buildtools, so that would be
https://github.com/bazelbuild/buildtools

Any objections or better ideas?

**Comment by pcj** [comment]
Tried to think of some clever "construction" related names (playing off buildozer), did not come up with anything better.

README needs paths updated.

**Comment by jwnimmer-tri** [comment]
The https://github.com/bazelbuild/buildtools/blob/master/WORKSPACE#L1 also needs updating.

**Comment by MarkusTeufelberger** [comment]
Caterbuilder? Toolshack?

**Comment by softprops** [comment]
What about splitting the tools into separate repos with separate release lifecycles?

**Comment by pmbethe09** [comment]
"What about splitting the tools into separate repos with separate release lifecycles?"

Seems overkill for the development velocity of these tools.

**Comment by pmbethe09** [comment]
buildtools was chosen
