### ISSUE TITLE
[buildifier] Autofix for rules not being global breaks your build

### ISSUE THREAD

**Issue by limdor** [bazelbuild/buildtools#785]
In case of python rules, buildifier warns you with the following message:
`Function "py_binary" is not global anymore and needs to be loaded from "@rules_python//python:defs.bzl".`
You can also automatically fix it and will add the following line at the top of your BUILD file.
`load("@rules_python//python:defs.bzl", "py_binary")`
The problem is that before the fix the build is working but after the fix is not working anymore.
Probably is because the rules need to be imported in the WORKSPACE file
https://github.com/bazelbuild/rules_python/releases
It would be nice if the fix would also add the required parts in the WORKSPACE file but I can understand that then is modifying a file that is not the active one. The other option would be to add a more explanatory message that guides the user on how to solve it.
Maybe the main question for the buildifier developers is if it is accepted that an automatic fix makes your build stop working.

**Comment by peloton-mqiu** [comment]
thanks @limdor for linking the release.

After adding the following line to my WORKSPACE, my bazel is able to find where to load `rules_python`:
```
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
http_archive(
    name = "rules_python",
    url = "https://github.com/bazelbuild/rules_python/releases/download/0.0.3/rules_python-0.0.3.tar.gz",
    sha256 = "e46612e9bb0dae8745de6a0643be69e8665a03f63163ac6610c210e80d14c3e4",
)
load("@rules_python//python:repositories.bzl", "py_repositories")
py_repositories()
```

**Comment by limdor** [comment]
Because buildifier does no longer warns about this anymore I do not think that it is worth to keep the issue opened. I will close it to contribute a bit on issue cleanup.
For more information see:
https://github.com/bazelbuild/bazel/issues/9006
https://github.com/bazelbuild/buildtools/issues/923
https://github.com/bazelbuild/buildtools/pull/952
