### ISSUE TITLE
buildifier should warn/move package() to just after load()

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/buildtools#817]
The semantics of package() warn that it
- is only allowed once
- it only impacts rules after it

That is subtle, non-declarative behavior. The fact that you can only use package() once also would imply that it is really package scoped, rather than lexically scoped.

We will (may?) eventually change that definition in Bazel so that package() always applies to all rules. We can get ahead of the curve by identifying and fixing BUILD files which might have potential ordering problems when we make that change.

**Comment by laurentlb** [comment]
As I mentioned, that's already implemented
https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#package-on-top

**Comment by aiuto** [comment]
Yes. I see. I missed it because I was looking in buildifier. 
It's never been exactly clear what capabilities are in buildifier and what is in buildozer, especially since they share a lot of code.
