### ISSUE TITLE
buildifier -v flag hangs

### ISSUE THREAD

**Issue by davinci26** [bazelbuild/buildtools#835]
Hey,

I installed buildifier via go get and when I run (same as #831):
```
C:\Users\sonanopo>buildifier -version
buildifier version: redacted
buildifier scm revision: redacted
```
while when I run only with `-v` buildifier *hangs*.

```
C:\Users\sonanopo>buildifier -v
<hangs>
```

My system is the following:

OS: Microsoft Windows Version 1809 (OS Build 17763.1217)
Go: go1.13 windows/amd64
Buildifier Version: unknown (installed via go get -u github.com/bazelbuild/buildtools/buildifier)

**Comment by vladmos** [comment]
`-v` is short for `--verbose`, not `--version`. Buildifier doesn't hang, it simply waits for stdin to format.

**Comment by davinci26** [comment]
Got confused while reading the help text. thanks for the reply.
