### ISSUE TITLE
buildifier support for other Starlark language features

### ISSUE THREAD

**Issue by garymm** [bazelbuild/buildtools#852]
We use the Starlark Go interpreter for some config files (not Bazel BUILD files), and we have a few additional Starlark features enabled that buildifier doesn't support, in particular we have these settings:

```go
resolve.AllowLambda = true
resolve.AllowNestedDef = true
resolve.AllowFloat = true
resolve.AllowSet = true
```

This is a request to support these features in buildifier.

**Comment by vladmos** [comment]
Do you need these features in the formatter?

They are not supported by Bazel, but at least some of them should be supported by Buildifier, e.g. there's a test for nested def statements: https://github.com/bazelbuild/buildtools/blob/master/build/testdata/051.in

**Comment by garymm** [comment]
I'm fairly sure I tried it yesterday and buildifer failed to format files with lambdas and floats.

**Comment by vladmos** [comment]
I've just checked that all the features mentioned above except floats are supported.

**Comment by garymm** [comment]
It doesn't support a lambda with **kwargs:

```
➜  echo 'x = lambda **kwargs: kwargs.get("foo")' | buildifier
<stdin>:1:14: syntax error near **
<stdin> # reformat
```

Starlark Go does support this.
Shall I file a separate bug about this, or re-open this one?

**Comment by vladmos** [comment]
Thanks, it's fine to track it here.
