### ISSUE TITLE
Unable to ignore linter errors

### ISSUE THREAD

**Issue by achew22** [bazelbuild/buildtools#867]
In a pr for starlib I tried to ignore the old [skylib](https://github.com/achew22/bazel-skylib/blob/db0951cdf14642a68cd807d7346899e9d07c2948/BUILD#L9) but it looks like that statement didn't ignore the lint warning. Is there anything that can be done about this?

[buildifier lint output](https://buildkite.com/bazel/bazel-skylib/builds/1074)

**Comment by vladmos** [comment]
This looks like a bug, thanks for reporting. I'll fix it next week.

**Comment by achew22** [comment]
Do I need to wait till next Monday to see this live on skylib?

**Comment by vladmos** [comment]
Try rerunning the job on the CI now, I've just released a new version of buildifier.
