### ISSUE TITLE
Once compiled buildifier via bazel how to install it?

### ISSUE THREAD

**Issue by endersaka** [bazelbuild/buildtools#881]
Once I successfully compiled buildifier with bazel, how am I supposed to install it (and, just in case, where is the binary)?

**Comment by vladmos** [comment]
Bazel should tell you where the location of the built binary, for example:

    Target //buildifier:buildifier up-to-date:
      bazel-bin/buildifier/darwin_amd64_stripped/buildifier

Alternatively, you can just download compiled binaries from here: https://github.com/bazelbuild/buildtools/releases

It doesn't need to be installed, just call the binary or copy it to a location listed in your `$PATH` variable.

**Comment by endersaka** [comment]
@vladmos thanks. I was not sure if the binary were self contained (or need some satellite files and where to install them), so that I can copy it in my PATH.
