### ISSUE TITLE
Error on "bazel run --remote_download_minimal //:buildifier"

### ISSUE THREAD

**Issue by vonschultz** [bazelbuild/buildtools#899]
### How to reproduce:

1. Set up a `WORKSPACE` and a `BUILD.bazel` according to the instructions in buildifier/README.md, so that you can `bazel run //:buildifier` successfully.
2. Run it with a remote cache server. `bazel run --remote_cache="grpc://${BAZEL_CACHE_HOST}:9092" --remote_download_minimal //:buildifier` for some value of `${BAZEL_CACHE_HOST}`.
3. If it wasn't already in the remote cache, do a `bazel clean`, and do `bazel run --remote_cache="grpc://${BAZEL_CACHE_HOST}:9092" --remote_download_minimal //:buildifier` again. The cache should be populated by now.

(For full disclosure, I'm using the `bazelisk` wrapper to start `bazel` here, and I believe it's `bazel-remote` running on the cache server.)

### Expected result

Successful return code `0`, no error messages.

### Actual result

Return code `127`, indicating failure. Error message:

`xargs: /home/chrvon/.cache/bazel/_bazel_chrvon/e8924209b57642c957efca185c7c7704/execroot/__main__/bazel-out/host/bin/external/com_github_bazelbuild_buildtools/buildifier/linux_amd64_stripped/buildifier: No such file or directory`

### Note

Without `--remote_download_minimal` it works.

**Comment by vladmos** [comment]
This looks like a problem with Bazel remote execution, please file a bug to https://github.com/bazelbuild/bazel/

**Comment by vonschultz** [comment]
Strictly speaking, no remote execution is taking place here.

But it looks like you're right. It's a problem with the Bazel remote cache, and there's apparently already a bug report about it: https://github.com/bazelbuild/bazel/issues/11920
