### ISSUE TITLE
Buildifier warns about lack of rules_cc; rules_cc says you don't have to use it

### ISSUE THREAD

**Issue by GMNGeoffrey** [bazelbuild/buildtools#923]
> native-cc: Function "cc_library" is not global anymore and needs to be loaded from "@rules_cc//cc:defs.bzl". (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#native-cc)

> There is no need to use rules from this repository just yet. If you want to use rules_cc anyway, add the following to your WORKSPACE file
https://github.com/bazelbuild/rules_cc#getting-started

These are clearly not compatible. In addition, the instruction to add rules_cc to your WORKSPACE file seem to be not accurate based on https://github.com/bazelbuild/bazel/issues/8743#issuecomment-704209848.

Please make the tools in the ecosystem and their documentation consistent.

Cross-posted as https://github.com/bazelbuild/rules_cc/issues/92

**Comment by vladmos** [comment]
@lberki to comment on whether the warning should be shown by default.

In general, these warning help users to migrate to a new API before the old API has been deprecated, so the warning is valid despite it's not necessary to load cc rules from the external repository at the moment.

**Comment by lberki** [comment]
I think it's better to remove the warning especially if it's worded that way -- I'd love the rules_cc migration to happen soon, but it will take a good while and until then, this is unnecessarily scary. That said, the `load()` statement still has value:

https://groups.google.com/g/bazel-discuss/c/XNvpWcge4AE

**Comment by GMNGeoffrey** [comment]
> I think it's better to remove the warning especially if it's worded that way -- I'd love the rules_cc migration to happen soon, but it will take a good while and until then, this is unnecessarily scary. That said, the `load()` statement still has value:
> 
> [groups.google.com/g/bazel-discuss/c/XNvpWcge4AE](https://groups.google.com/g/bazel-discuss/c/XNvpWcge4AE)

I don't totally follow this thread. Should I add the loads? I'm currently rather confused by the behavior where I can add a load for `load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library")` even though I haven't configured `rules_cc` in our WORKSPACE

**Comment by chandlerc** [comment]
Any chance we could get some clarity here? It's been a month of having buildifier insist on one thing and the docs on another.

I don't have any preference for what the plan is or how we get there. I just want either clear guidance that adding the loads is a valid and good thing to do, or I want buildifier to not lint on them. Otherwise we continue to miss potentially important buildifier warnings because of the noise of these.

**Comment by danila-piatov** [comment]
Was there a regression? Buildifier 8.0.3 is still showing me this warning.
