### ISSUE TITLE
Buildifier confused about return values in nested methods

### ISSUE THREAD

**Issue by bpastene** [bazelbuild/buildtools#926]
eg:
```
def outer():
  def inner():
    return 0

  i = inner()
```

Buildifier throws the following error on that code snippet:
return-value: Some but not all execution paths of "outer" return a value

But what executions of outer() have a return value? I would suspect that that's safe/valid starlark, but buildifier thinks otherwise?

**Comment by vladmos** [comment]
This warning was implemented when Starlark didn't have implementations with allowed nested functions, it doesn't handle such situations correctly.
