### ISSUE TITLE
buildozer: WORKSPACE search is surprising for Buck users

### ISSUE THREAD

**Issue by swolchok** [bazelbuild/buildtools#93]
Buck doesn't have an equivalent to Bazel's `WORKSPACE` files. Normally, this isn't a problem -- the search fails and buildozer assumes `$PWD` is the root directory. Because Mac OS uses a case-insensitive filesystem, this causes surprising behavior for buildozer+Buck users who happen to have a file or directory called `workspace` in their home directory (e.g., because they've used Eclipse).

Passing `-root_dir .` (and running from the Buck root) is a workaround, but it's not an obvious one; the same seems true for adding an otherwise-unnecessary `WORKSPACE` file to the Buck root. Perhaps there is something we can do in Buildozer to make using it easier for Buck users?

**Comment by pmbethe09** [comment]
How would does BUCK find the // dir?

**Comment by swolchok** [comment]
AFAICT, buck relies on the presence of `.buckconfig` in much the same way Bazel relies on `WORKSPACE` (see https://github.com/facebook/buck/blob/master/programs/buck_project.py#L124). https://buckbuild.com/concept/buckconfig.html  says that the root *may* contain `.buckconfig`, but I suspect that it should say *must*.

**Comment by pmbethe09** [comment]
if you want to add that feature -- looking for .buckconfig when looking for WORKSPACE fails?

**Comment by swolchok** [comment]
> looking for .buckconfig when looking for WORKSPACE fails?
I'm generally not bothered by the case when looking for WORKSPACE fails. The problem is when it succeeds because of a directory structure like:

```
- ~/workspace # left over from eclipse or just seemed like a good name for a folder
- ~/somebuckrepo
```

`somebuckrepo` will not necessarily contain `WORKSPACE`, so buildozer's upward `WORKSPACE` search will reach `~/workspace`, which will match because Macs have case-insensitive filesystems, and then buildozer will conclude that `~` is the repo root.

Rather than doing two sequential searches, which wouldn't avoid this problem, would it be reasonable to do a single search that checked for either `WORKSPACE` or `.buckconfig` in each directory before climbing to the parent directory? That would confuse buildozer if a Buck project was kept inside a Bazel one or vice versa, but it doesn't seem like there's any good solution to nested projects if the tool is going to support both build systems.
