### ISSUE TITLE
Unclear Documentation in buildifier/README.md

### ISSUE THREAD

**Issue by ssiano** [bazelbuild/buildtools#936]
The documentation starting at Line 29 ("Buildifier automatically detects ...") is unclear.

Something seems to be missing from the text starting with "If you", which is followed by an example usage command and a paragraph about a different point.

**Comment by vladmos** [comment]
Thanks, the documntation does not only have a typo but is also out of date.

**Comment by ssiano** [comment]
Thanks @vladmos!
