### ISSUE TITLE
Executing buildifier.exe results in RuntimeException for Android project

### ISSUE THREAD

**Issue by Srikanth-Kb** [bazelbuild/buildtools#941]
Using `buildifier.exe` (version 3.4.0) on Windows 10, when we execute the lint check with this file, we are observing the following `Runtime error` exception:
![image](https://user-images.githubusercontent.com/36214903/104454890-87810100-55cc-11eb-914e-5274425bf4cd.png)

**Comment by vladmos** [comment]
FS errors are currently not handled correctly. There's probably an access error which causes directory traversal to fail, but it should be reported instead of crashing buildifier with an NPE.
