### ISSUE TITLE
Could please use Go modules to manage dependencies?

### ISSUE THREAD

**Issue by Loyalsoldier** [bazelbuild/buildtools#961]
The release of Go v1.16, which sets `GO111MODULE` env to `on` by default (ref: [https://golang.org/doc/go1.16#go-command](https://golang.org/doc/go1.16#go-command)), leads to build failure of Homebrew formula `buildifier` and `buildozer`. Thus they disable them for now in PR https://github.com/Homebrew/homebrew-core/pull/71330

If to use Go modules to manage dependencies, it'll be great for downstreams (eg. Homebrew) to build and install them.

**Comment by Loyalsoldier** [comment]
I have attempted to file a PR for this but build failed https://github.com/bazelbuild/buildtools/pull/959

**Comment by pmbethe09** [comment]
So the idea of Go modules is when you make a breaking API change, you increase the major version.
At this time, we have not made any breaking changes that I am aware of, so even though we are version 4.0.0 it isn't really a Go 'v4' implying a 3rd breaking API change.

So I think all we need here is a go.mod and go.sum file to make this work?

**Comment by Loyalsoldier** [comment]
Yeah, the idea is to make builds reproducible for Golang.

**Comment by Loyalsoldier** [comment]
You guys should release a new version so that downstream (eg. Homebrew) can use the new version commit to re-enable, build and install `buildifier` and `buildozer`.

https://github.com/Homebrew/homebrew-core/pull/71330#issuecomment-787739192

**Comment by vladmos** [comment]
I've just released 4.0.1

**Comment by Loyalsoldier** [comment]
@vladmos Cool!
