### ISSUE TITLE
The introduction of buildifier_test removed the option to run check/lint on all BUILD files.

### ISSUE THREAD

**Issue by mishas** [bazelbuild/buildtools#968]
I used to have a `buildifier` rule that ran in a CI, that just warned on format/lint warnings for all files.

With the introduction of buildifier_test (in #929), this now became "deprecated".
It seems like I'm suppose to use `buildifier_test` for checks/lint, but then I have to have all my BUILD (and .bzl) files in the `srcs` fields, which is not an easy task in many projects :(

Even when running the test using `bazel run` (instead of `bazel test`), the `TEST_WORKSPACE` env var is defined, and thus only the runfiles-collected files are checked.

Suggestion for solution:
It seems like the `BUILD_WORKSPACE_DIRECTORY` env var is only available when running with `bazel run` (https://docs.bazel.build/versions/master/user-manual.html#run). We can check `TEST_WORKSPACE && !BUILD_WORKSPACE_DIRECTORY` (pseudo code) to decide if to run on real code or not.

**Comment by sudoforge** [comment]
Nice catch. I'll spend some time this upcoming weekend to write some tests for `buildifier_test`.

**Comment by jfirebaugh** [comment]
Seems like this is not actually fixed? `buildifier_test` still requires a `srcs` attribute.

**Comment by sudoforge** [comment]
@jfirebaugh This issue had nothing to do with the required `srcs` attribute on `buildifier_test`.

**Comment by jfirebaugh** [comment]
> It seems like I'm suppose to use `buildifier_test` for checks/lint, but then I have to have all my BUILD (and .bzl) files in the `srcs` fields, which is not an easy task in many projects :(

...but ok, sure, I'll open a new bug.

**Comment by jfirebaugh** [comment]
https://github.com/bazelbuild/buildtools/issues/1075

**Comment by sudoforge** [comment]
For clarity, this issue was in relation to not being able to `bazel run` on `buildifier_test` targets with consistency to the set of files that were being checked. I'll take a look at #1075.
