### ISSUE TITLE
Make "_buildifier" attribute in "buildifier_attr_factory" public

### ISSUE THREAD

**Issue by dududko** [bazelbuild/buildtools#974]
I want to use a pre-build binary in the `buildifier` bazel rule instead of building it with bazel, and it is not so simple due to the fact the `_buildifier` attribute is private. If it was public like in gazelle, it would make the life much easier. 

Could you please make this attribute public ( i.e by renaming it `_buildifier` -> `buildifier`) ?

**Comment by vladmos** [comment]
Could you please send a pull request with the change?
