### ISSUE TITLE
Add labels.Expand function

### ISSUE THREAD

**Issue by zelliott** [bazelbuild/buildtools#984]
There's a `labels.Shorten` function that returns the "shortened" form of a label, i.e. `//foo:foo` --> `//foo`. It would be useful to have the inverse of this, maybe `labels.Expand`, that does basically the opposite.

I'm happy to contribute this if the bazelbuild team is supportive.

**Comment by pmbethe09** [comment]
labels.Parse already does this

**Comment by pmbethe09** [comment]
https://github.com/bazelbuild/buildtools/blob/master/labels/labels.go#L66

pass //some/target get back Label{"", "some/target", "target"

**Comment by zelliott** [comment]
Yeah, I just didn't like the string concatenation I needed to do afterwards (i.e. `"//" + label.Package + ":" + label.Target`) and wasn't sure if it worked in all edge cases.

**Comment by pmbethe09** [comment]
maybe then what you want is a method Expanded on Label?

**Comment by zelliott** [comment]
That would work, yes.

**Comment by zelliott** [comment]
Does it make sense to re-open & rename this issue then?

**Comment by pmbethe09** [comment]
that works

**Comment by laurentlb** [comment]
Why would you want to get the non-canonical form? I'm not sure we want to encourage this.

Feel free to create a helper function in your code if you do need it.

**Comment by zelliott** [comment]
My program has a dependency on a service that - for some reason - always returns labels in the expanded form. My program also takes a handful of user-specified labels as input. It's easier/more efficient to expand the user-specified labels (of which there are only a few) than it is to shorten the thousands the labels returned by this service.

Is using a label's expanded form _discouraged_ by Bazel? I don't see that mentioned anywhere at https://docs.bazel.build/versions/main/build-ref.html#labels. I see:

> When it matches the last component of the package path, it, and the colon, may be omitted.

(emphasis on _may_, instead of _should_).
